
(()=>{
 let recommendedLesson=null;
 function openNextLesson(){
  window.openJapaneseMinerV5?.('map');
  const lesson=recommendedLesson;if(!lesson)return;
  setTimeout(()=>{const [language,stage,section,index]=lesson.id.split(':');const selector=language==='ja'?(section==='alphabet'?`[data-world-family-stage="${stage}"][data-world-family="${index}"]`:`[data-world-lesson-stage="${stage}"][data-world-lesson-section="${section}"][data-world-lesson-level="${index}"]`):`[data-lm-course-mine="${stage}"][data-lm-course-section="${section}"][data-lm-course-lesson="${index}"]`;const button=document.querySelector(selector);if(button&&!button.disabled)button.click();},100);
 }
 const actions={nextLesson:openNextLesson,language:()=>document.getElementById('lmChangeLanguageBtn')?.click(),learn:()=>{document.getElementById('quickMineBtn')?.click();},explore:()=>window.openJapaneseMinerV5?.('map'),progress:()=>window.openLanguageMinerMyProgress?.(),notebook:()=>window.openJapaneseMinerNotebook?.(),family:()=>window.LanguageMinerParentTeacher?.open(),settings:()=>window.openJapaneseMinerSettings?.(),calendar:()=>document.getElementById('studyCalendarBtn')?.click(),health:()=>window.openJapaneseMinerDashboard?.('health'),inventory:()=>window.openJapaneseMinerDashboard?.('inventory'),shop:()=>document.querySelector('[data-menu-action="shop"]')?.click(),character:()=>document.querySelector('[data-feature-open="profile"]')?.click(),menu:()=>document.getElementById('gameMenuBtn').click(),account:()=>window.openLanguageMinerAccountSupport?.(),logout:()=>document.getElementById('logoutBtn')?.click(),admin:()=>document.getElementById('developerBtn')?.click(),guide:()=>document.getElementById('v6CoachButton')?.click()};
 const entries=[['learn','◈','Learn'],['explore','◇','Expedition Hub'],['progress','▥','My Progress'],['notebook','▤','Notebook'],['family','♧','Parent / Teacher'],['settings','⚙','Settings']];
 const nav=document.createElement('nav');nav.className='adventure-nav';nav.setAttribute('aria-label','Adventure navigation');nav.innerHTML='<a class="adventure-brand" href="#">⚒<span>LANGUAGE<br>MINER</span></a><div class="adventure-avatar"><button type="button" data-adventure="character" class="adventure-character-link">⚒ Character &amp; equipment</button><strong>Explorer</strong><small>Your learning adventure</small></div>'+entries.map(([id,icon,label])=>`<button data-adventure="${id}" ${id==='learn'?'class="selected"':''}><span>${icon}</span>${label}</button>`).join('')+'<button data-adventure="menu"><span>☰</span>All features</button><button data-adventure="account"><span>☁</span>Account & Support</button><button data-adventure="logout"><span>↪</span>Log out</button><button data-adventure="admin" hidden><span>⚙</span>Admin</button>';document.body.append(nav);
 const today=document.createElement('aside');today.className='adventure-today';today.innerHTML='<h2>Today’s journey</h2><div id="adventureMetrics"></div><div class="adventure-next"><span>YOUR NEXT STOP</span><img class="adventure-trail-art" src="adventure-world.png" alt="Lantern-lit path through the crystal mine"><h3 id="adventureNextName">Choose a lesson</h3><p id="adventureNextDetail">Continue your language adventure.</p><button data-adventure="nextLesson">Open next lesson →</button></div><div class="adventure-guide"><span class="v6-gnome" aria-hidden="true"><i class="gnome-hat"></i><i class="gnome-face"></i><i class="gnome-nose"></i><i class="gnome-beard"></i><i class="gnome-body"></i></span><h3>A little help?</h3><p>Your study guide is here whenever you need it.</p><button data-adventure="guide">Ask your guide</button></div><button data-adventure="progress">View my progress →</button>';document.body.append(today);
 const mobile=document.createElement('nav');mobile.className='adventure-mobile';mobile.setAttribute('aria-label','Mobile navigation');mobile.innerHTML=[['learn','◈','Learn'],['explore','◇','Explore'],['progress','▥','Progress'],['menu','☰','Menu']].map(([id,icon,label])=>`<button data-adventure="${id}"><span>${icon}</span>${label}</button>`).join('');document.body.append(mobile);
 document.addEventListener('click',e=>{const b=e.target.closest('[data-adventure]');if(!b)return;setTimeout(()=>{if(b.dataset.adventure!=='menu')window.closeGameMenu?.();actions[b.dataset.adventure]?.();},0);});
 const tools=document.createElement('section');tools.className='adventure-tools';tools.setAttribute('aria-label','Player tools');tools.innerHTML=[['calendar','Calendar'],['health','Health'],['inventory','Inventory'],['shop','Shop'],['character','Character'],['notebook','Notebook'],['family','Parent / Teacher'],['guide','Ask your guide'],['nextLesson','Next lesson']].map(([id,label])=>`<button type="button" data-adventure="${id}">${label}</button>`).join('');document.querySelector('.app>header').after(tools);
 const next=document.createElement('button');next.id='adventureContinue';next.textContent='Next question →';next.onclick=()=>{document.getElementById('quickMineBtn')?.click();update();};document.querySelector('#challengeArea').parentElement.append(next);
 function update(){
  const profile=window.japaneseMinerActiveProfile?.();document.body.classList.toggle('adventure-signed-in',!!profile);
  const name=nav.querySelector('.adventure-avatar strong');if(name&&name.textContent!==profile?.name)name.textContent=profile?.name||'Player';
  nav.querySelector('[data-adventure="admin"]').hidden=document.getElementById('developerBtn')?.hidden!==false;
  const grid=document.querySelector('.menu-wheel,.game-menu-grid');
  if(grid&&!grid.querySelector('[data-adventure="logout"]'))for(const [id,label] of [['calendar','Study calendar'],['health','Practice health'],['logout','Log out'],['admin','Admin'],['guide','Study guide']]){const b=document.createElement('button');b.type='button';b.dataset.adventure=id;b.dataset.menuCategoryName='player';const title=document.createElement('strong');title.textContent=label;b.appendChild(title);grid.appendChild(b);}
  if(grid)for(const b of grid.querySelectorAll('[data-adventure]')){const layout=grid.closest('.miner-interface-menu');b.hidden=(layout&&layout.dataset.category!=='player')||(b.dataset.adventure==='admin'&&document.getElementById('developerBtn')?.hidden!==false);}

  const summary=window.LanguageMinerReadOnly?.learnerSummary?.(window.japaneseMinerActiveProfile?.()?.id);
  if(summary){const day=new Date(),key=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,'0')}-${String(day.getDate()).padStart(2,'0')}`,ms=summary.activity.days.find(x=>x.date===key)?.milliseconds||0;document.getElementById('adventureMetrics').innerHTML=`<p><b>${Math.floor(ms/60000)} min</b><span>studied today</span></p><p><b>${summary.course.lessons.counts.completed}</b><span>lessons complete</span></p><p><b>${summary.activity.currentStreak} days</b><span>current streak</span></p>`;}
  const lessons=summary?.course?.lessons?.items||[];
  recommendedLesson=lessons.find(item=>item.unlocked&&!item.completed)||null;
  const nextName=document.getElementById('adventureNextName'),nextDetail=document.getElementById('adventureNextDetail');
  nextName.textContent=recommendedLesson?.name||'Explore your course';
  nextDetail.textContent=recommendedLesson?`${recommendedLesson.level} · ${recommendedLesson.mastery}% mastery`:'Choose an available lesson or review in the Expedition Hub.';
  const nextAction=today.querySelector('[data-adventure="nextLesson"]');nextAction.textContent=recommendedLesson?'Open next lesson →':'Open Expedition Hub →';
  document.getElementById('lmChangeLanguageBtn')?.setAttribute('aria-label','Change your known and learning languages');
  const title=document.querySelector('.mine-title');const label=document.getElementById('stageName')?.textContent;if(title&&label&&title.textContent!==label)title.textContent=label;
  next.hidden=!profile;next.textContent=document.getElementById('quickMineLabel')?.textContent?.trim()||'Start or return to question';
 }
 window.addEventListener('jm-profile-loaded',update);window.addEventListener('jm-profile-logged-out',update);update();setInterval(update,3000);
})();
