// Language Miner v6.4.171 Tier 3 Arcade — strict native-language spoken study games.
(()=>{
'use strict';
const GAMES=[
 {id:'memory',icon:'🧠',name:'Memory Mine',tag:'Memorization game',description:'Reveal cards and remember six learning-language word pairs.',instruction:'Match every learning-language word with its known-language meaning.'},
 {id:'matching',icon:'🔗',name:'Crystal Match',tag:'Matching game',description:'Connect words to their meanings before the clock runs out.',instruction:'Select a learning word, then select its matching meaning.'},
 {id:'shooter',icon:'🚀',name:'Star Word Defender',tag:'Timed alignment game',description:'Move the arrow beneath the correct falling word to score.',instruction:'Align the arrow with the matching word before it reaches the target line.'},
 {id:'echo',icon:'🔊',name:'Echo Cavern',tag:'Listening challenge',description:'Listen carefully and identify the spoken word or sentence.',instruction:'Choose the meaning that matches what you hear.'},
 {id:'grammar',icon:'⚒️',name:'Grammar Forge',tag:'Sentence building game',description:'Forge complete sentences by arranging words in the correct order.',instruction:'Tap the language pieces in order, then test your sentence.'},
 {id:'treasure',icon:'🗺️',name:'Treasure Translator',tag:'Direction translation game',description:'Translate map clues and guide your miner to buried treasure.',instruction:'Read each direction clue and choose the correct path.'},
 {id:'crystal-memory',icon:'💎',name:'Crystal Memory Match',tag:'Three-way memory game',description:'Match each word with its meaning and spoken-audio crystal.',instruction:'Reveal and connect the learning word, meaning, and audio crystal.'},
 {id:'impostor',icon:'🕵️',name:'Impostor Word',tag:'Vocabulary category game',description:'Find the one word that does not belong with the others.',instruction:'Identify the unrelated word, then review its meaning.'}
];
const PAIRS_FALLBACK=[['人','person'],['日','day / sun'],['月','moon / month'],['火','fire'],['水','water'],['木','tree'],['山','mountain'],['川','river'],['口','mouth'],['目','eye'],['手','hand'],['友達','friend']];
const VOICE_TAGS={ja:'ja-JP',zh:'zh-CN',ko:'ko-KR',es:'es-ES',fr:'fr-FR',de:'de-DE',ru:'ru-RU',it:'it-IT',pt:'pt-BR',vi:'vi-VN',th:'th-TH',tr:'tr-TR',id:'id-ID',pl:'pl-PL',el:'el-GR',uk:'uk-UA',en:'en-US'};
const IMPOSTOR_GROUPS=[
 {id:'nature',label:'Nature',ids:[2,3,4,5,6,8,9,10]},
 {id:'body',label:'Body parts',ids:[12,13,14,15,16,131]},
 {id:'actions',label:'Actions',ids:[31,32,33,34,35,36,37,38,39,40,46,48,58,59]},
 {id:'time',label:'Time words',ids:[87,88,89,93,94,95,96,124,126,127]},
 {id:'people',label:'People',ids:[1,72,73,74,137,138,139,160,206,211]},
 {id:'food',label:'Food and drink',ids:[65,66,84,125,147,207,212,219]}
];
const $=selector=>document.querySelector(selector),escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const shuffle=values=>{const copy=[...values];for(let index=copy.length-1;index>0;index--){const swap=Math.floor(Math.random()*(index+1));[copy[index],copy[swap]]=[copy[swap],copy[index]];}return copy;};
const tier=()=>Math.max(0,Number(window.japaneseMinerSupporterTier?.()||0));
function ensure(){state.v6=state.v6&&typeof state.v6==='object'?state.v6:{};state.v6.arcadeOwned=Array.isArray(state.v6.arcadeOwned)?[...new Set(state.v6.arcadeOwned.map(String).filter(id=>GAMES.some(game=>game.id===id)))]:[];state.v6.arcadeBest=state.v6.arcadeBest&&typeof state.v6.arcadeBest==='object'&&!Array.isArray(state.v6.arcadeBest)?state.v6.arcadeBest:{};if(typeof state.v6.arcadeBagExpanded!=='boolean')state.v6.arcadeBagExpanded=true;}
function owned(id){ensure();return state.v6.arcadeOwned.includes(String(id));}
function claim(id){ensure();if(tier()<3)return false;if(!GAMES.some(game=>game.id===id))return false;if(!owned(id)){state.v6.arcadeOwned.push(id);save();}return true;}
function gate(feature='Arcade mini games'){return window.japaneseMinerSupporterGate?.(3,feature)||'<p>Patreon Tier 3 is required.</p>';}
function shopMarkup(){ensure();return `<section class="arcade-collection-head"><span>PATREON TIER 3 · $5 PATREON COLLECTION</span><h3>🕹️ Study Arcade</h3><p>Claim each mini game once, then launch it anytime from the Shop or your Bag. No Nuggets are charged.</p></section><div class="arcade-library">${GAMES.map(game=>gameCard(game,'shop')).join('')}</div>`;}
function bagMarkup(){ensure();const claimed=GAMES.filter(game=>owned(game.id)),expanded=state.v6.arcadeBagExpanded!==false;return `<div class="owned-inventory-title arcade-bag-title"><span>Tier 3 game bag · $5 Patreon</span><h3>🕹️ Study Arcade</h3><p>${claimed.length?`${claimed.length} mini game${claimed.length===1?'':'s'} ready to play.`:'Claim mini games from the Shop, then they will appear here.'}</p><button class="arcade-bag-toggle" type="button" data-arcade-bag-toggle aria-expanded="${expanded}" aria-controls="arcadeBagLibrary" aria-label="${expanded?'Collapse':'Expand'} Study Arcade"><span aria-hidden="true">${expanded?'▲':'▼'}</span></button></div><div id="arcadeBagLibrary" class="arcade-library arcade-bag-library" ${expanded?'':'hidden'}>${(claimed.length?claimed:GAMES).map(game=>gameCard(game,claimed.length?'bag':'unclaimed')).join('')}</div>`;}
function gameCard(game,location){const has=owned(game.id),best=state.v6.arcadeBest[game.id],disabled=location==='unclaimed';return `<article class="arcade-game-card ${has?'owned':'claimable'} ${disabled?'unclaimed':''}"><div class="arcade-game-icon">${game.icon}</div><span>${escape(game.tag)}</span><h3>${escape(game.name)}</h3><p>${escape(game.description)}</p><small>${best?`Best: ${escape(bestLabel(game.id,best))}`:has?'Unlocked in your Bag':'Included with Tier 3 · $5 Patreon'}</small><button type="button" data-arcade-${has?'play':'claim'}="${game.id}" ${disabled?'disabled':''}>${has?'Play now':'Unlock mini game'}</button></article>`;}
function bind(container,refresh){container?.querySelectorAll('[data-arcade-claim]').forEach(button=>button.addEventListener('click',()=>{if(claim(button.dataset.arcadeClaim)){setMessage?.('Mini game unlocked and added to your Bag.','correct');refresh?.();}}));container?.querySelectorAll('[data-arcade-play]').forEach(button=>button.addEventListener('click',()=>open(button.dataset.arcadePlay)));container?.querySelectorAll('[data-arcade-lesson-select]').forEach(select=>select.addEventListener('change',()=>{if(selectLesson(select.value))refresh?.();}));const bagToggle=container?.querySelector('[data-arcade-bag-toggle]');if(bagToggle)bagToggle.addEventListener('click',()=>{ensure();const expanded=bagToggle.getAttribute('aria-expanded')!=='true',library=container.querySelector('#arcadeBagLibrary'),arcadeName=window.LanguageMinerI18n?.translate?.('Study Arcade')||'Study Arcade';state.v6.arcadeBagExpanded=expanded;bagToggle.setAttribute('aria-expanded',String(expanded));bagToggle.setAttribute('aria-label',window.LanguageMinerI18n?.t?.(expanded?'collapse':'expand',{value:arcadeName})||`${expanded?'Collapse':'Expand'} Study Arcade`);bagToggle.querySelector('span').textContent=expanded?'▲':'▼';if(library)library.hidden=!expanded;container.classList.toggle('collapsed',!expanded);save();});}
function knownMeaning(learn,fallback,known){const data=window.LANGUAGE_MINER_MULTILINGUAL_COURSE_DATA||{};for(const group of ['vocabulary','grammar','sentences']){const item=(data[group]||[]).filter(entry=>window.LanguageMinerVocabulary?.available(entry)!==false).find(entry=>String(entry?.forms?.ja||'')===String(learn||''));if(item?.forms?.[known])return String(item.forms[known]);}return String(fallback||learn||'');}
function japaneseLesson(stage=typeof selectedStageIndex==='function'?selectedStageIndex():0,section='',lesson=-1){
 const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{},known=String(settings.known||'en');stage=Number(stage)||0;
 try{
  if(stage<=1){const families=kanaFamiliesForStage(stage),index=lesson>=0?Number(lesson):Number(state.kanaFamilyLevel?.[stage===1?'katakana':'hiragana']||0),family=families[index]||families[0],pairs=(family?.entries||[]).map(([character,romanization],itemIndex)=>({id:`ja-${stage}-kana-${index}-${itemIndex}`,learn:String(character),meaning:String(romanization)}));return {key:`ja:${stage}:kana:${index}`,learning:'ja',known,mine:stage,section:'alphabet',lesson:index,label:`${stages[stage]?.name||stages[stage]?.label||'Japanese'} · ${family?.name||`Lesson ${index+1}`}`,pairs};}
  section=section||currentJlptSection(stage);const level=lesson>=0?Number(lesson):currentJlptSectionLevel(stage,section),items=jlptSectionLevels(stage,section)[level]||[],spec=jlptSectionSpec(section),pairs=[];
  items.forEach((item,index)=>{const learn=String(item?.primary||item?.jp||''),fallback=item?.meaning||item?.secondary||item?.detail;if(learn&&fallback&&learn!==String(fallback))pairs.push({id:`ja-${stage}-${section}-${level}-${item?.masteryId||item?.key||index}`,learn,meaning:knownMeaning(learn,fallback,known)});});
  return {key:`ja:${stage}:${section}:${level}`,learning:'ja',known,mine:stage,section,lesson:level,label:`${stages[stage]?.label||stages[stage]?.name||'Japanese'} · ${spec?.name||section} · Lesson ${level+1}`,pairs};
 }catch{return null;}
}
function japaneseLessonOptions(){const options=[];try{for(let stage=0;stage<stages.length;stage++){if(!isStageUnlocked(stage))continue;if(stage<=1){kanaFamiliesForStage(stage).forEach((family,index)=>{if(kanaFamilyUnlocked(stage,index)&&family.entries.length)options.push({key:`ja:${stage}:kana:${index}`,label:`${stages[stage]?.name||stages[stage]?.label||'Japanese'} · ${family.name||`Lesson ${index+1}`}`});});continue;}for(const spec of JLPT_SECTION_SPECS){jlptSectionLevels(stage,spec.id).forEach((items,index)=>{if(items.length&&jlptSectionLevelUnlocked(stage,spec.id,index))options.push({key:`ja:${stage}:${spec.id}:${index}`,label:`${stages[stage]?.label||stages[stage]?.name||'Japanese'} · ${spec.name} · Lesson ${index+1}`});});}}}catch{}return options;}
function currentLesson(){const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{},learning=String(settings.learning||'ja'),known=String(settings.known||'en');if(learning!=='ja'){const selected=window.LanguageMinerCourseLesson?.current?.();if(selected?.pairs?.length)return selected;}else{const selected=japaneseLesson();if(selected?.pairs?.length)return selected;}const source=window.LANGUAGE_MINER_MULTILINGUAL_COURSE_DATA?.vocabulary||[],pairs=[];for(const item of source){if(window.LanguageMinerVocabulary?.available(item)===false)continue;const learn=item?.forms?.[learning],meaning=item?.forms?.[known];if(learn&&meaning&&learn!==meaning&&!pairs.some(pair=>pair.learn===learn))pairs.push({id:`fallback-course-${item.id}`,learn:String(learn),meaning:String(meaning)});if(pairs.length>=25)break;}if(!pairs.length)PAIRS_FALLBACK.forEach(([learn,meaning],index)=>pairs.push({id:`fallback-${index}`,learn,meaning}));return {key:'fallback',learning,known,mine:0,section:'vocabulary',lesson:0,label:'Current lesson',pairs};}
function lessonOptions(){const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{};return String(settings.learning||'ja')==='ja'?japaneseLessonOptions():(window.LanguageMinerCourseLesson?.options?.()||[]);}
function selectLesson(key){key=String(key||'');const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{};if(String(settings.learning||'ja')!=='ja')return window.LanguageMinerCourseLesson?.select?.(key)===true;const match=/^ja:(\d+):([a-z]+):(\d+)$/.exec(key);if(!match)return false;const stage=Number(match[1]),section=match[2],lesson=Number(match[3]);try{selectStage(stage,false);if(stage<=1)selectKanaFamily(stage,lesson);else selectJlptSectionLevel(stage,section,lesson);return currentLesson().key===key;}catch{return false;}}
function lessonSourceMarkup(source,{selectable=false}={}){const options=selectable?lessonOptions():[],control=selectable&&options.length?`<select data-arcade-lesson-select aria-label="Current lesson">${options.map(option=>`<option value="${escape(option.key)}" ${option.key===source.key?'selected':''}>${escape(option.label)}</option>`).join('')}</select>`:`<strong>${escape(source.label)}</strong>`;return `<div class="arcade-lesson-source"><span>Current lesson</span>${control}</div>`;}
function vocabularyPairs(count=12){const source=currentLesson(),pairs=shuffle(source.pairs).slice(0,Math.max(2,Math.min(Number(count)||12,source.pairs.length)));return {source,pairs};}
function arcadeMode(){return state.quizDifficulty==='hard'?'hard':'easy';}
function modeMarkup(id){const mode=arcadeMode();return `<div class="arcade-mode" role="group" aria-label="Arcade difficulty"><span>Challenge mode</span><button type="button" data-arcade-mode="easy" data-arcade-mode-game="${id}" class="${mode==='easy'?'selected':''}" aria-pressed="${mode==='easy'}">🌱 Easy</button><button type="button" data-arcade-mode="hard" data-arcade-mode-game="${id}" class="${mode==='hard'?'selected':''}" aria-pressed="${mode==='hard'}">⛏️ Hard</button></div>`;}
function bindMode(id){document.querySelectorAll(`[data-arcade-mode-game="${id}"]`).forEach(button=>button.onclick=()=>{state.quizDifficulty=button.dataset.arcadeMode==='hard'?'hard':'easy';save();start(id);});}
function languageSettings(){const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{};return {learning:String(settings.learning||'ja'),known:String(settings.known||'en')};}
function speakArcade(text,language,rate=1){if(!text)return false;const tag=VOICE_TAGS[language]||language;if(!tag)return false;if(window.LanguageMinerSpeech?.pronounce)return window.LanguageMinerSpeech.pronounce(String(text),tag,rate);if(window.LanguageMinerSpeech?.speak)return window.LanguageMinerSpeech.speak(String(text),tag,rate);return false;}
function courseItems(group='vocabulary'){const {learning,known}=languageSettings(),items=window.LANGUAGE_MINER_MULTILINGUAL_COURSE_DATA?.[group]||[];return items.filter(item=>window.LanguageMinerVocabulary?.available(item)!==false).map(item=>({id:String(item.id),topic:Number(item.topic)||0,learn:String(item?.forms?.[learning]||''),meaning:String(item?.forms?.[known]||''),forms:item.forms||{}})).filter(item=>item.learn&&item.meaning&&item.learn!==item.meaning);}
function sentenceTokens(text,language){text=String(text||'').trim();if(!text)return[];if(/\s/.test(text))return text.split(/\s+/).filter(Boolean);try{if(typeof Intl?.Segmenter==='function'){const segmenter=new Intl.Segmenter(VOICE_TAGS[language]||language,{granularity:'word'}),parts=[...segmenter.segment(text)].map(item=>item.segment.trim()).filter(Boolean);if(parts.length>1)return parts;}}catch{}return [...text].filter(character=>character.trim());}
function sentenceBank(){const {learning,known}=languageSettings();return courseItems('sentences').map(item=>({...item,tokens:sentenceTokens(item.learn,learning),learning,known})).filter(item=>item.tokens.length>=3&&item.tokens.length<=14);}
function repeatPairs(pairs,count){const shuffled=shuffle(pairs),result=[];if(!shuffled.length)return result;for(let index=0;index<count;index++)result.push(shuffled[index%shuffled.length]);return result;}
function notifyArcade(correct,message=''){window.dispatchEvent(new CustomEvent('lm-character-animation',{detail:{state:correct?'correct':'incorrect',context:'arcade',activity:session?.id||''}}));const status=$('#arcadeLiveStatus');if(status)status.textContent=message;}
function bindGameLessonSelector(id){const select=$('[data-arcade-lesson-select]');if(select)select.onchange=()=>{if(selectLesson(select.value))start(id);};}
let session=null,timer=null,animation=null;
function shell(){if($('#arcadeOverlay'))return;document.body.insertAdjacentHTML('beforeend',`<div id="arcadeOverlay" class="arcade-overlay" aria-hidden="true"><section class="arcade-panel" role="dialog" aria-modal="true" aria-labelledby="arcadeTitle"><header><button id="arcadeBack" type="button">← Arcade</button><div><span>Tier 3 Study Arcade</span><h2 id="arcadeTitle">Mini game</h2></div><button id="arcadeClose" type="button" aria-label="Close mini game">×</button></header><main id="arcadeContent"></main></section></div>`);$('#arcadeClose').onclick=close;$('#arcadeBack').onclick=renderLibrary;$('#arcadeOverlay').onclick=event=>{if(event.target.id==='arcadeOverlay')close();};}
function open(id=''){ensure();if(tier()<3){window.openJapaneseMinerPatreon?.();return false;}if(id&&!owned(id)){window.openJapaneseMinerArcadeShop?.();return false;}closeOtherOverlays();shell();$('#arcadeOverlay').classList.add('open');$('#arcadeOverlay').setAttribute('aria-hidden','false');window.syncJapaneseMinerPageScroll?.();if(id)start(id);else renderLibrary();return true;}
function close(){stopRuntime();$('#arcadeOverlay')?.classList.remove('open');$('#arcadeOverlay')?.setAttribute('aria-hidden','true');window.syncJapaneseMinerPageScroll?.();}
function stopRuntime(){if(timer){clearInterval(timer);timer=null;}if(animation){cancelAnimationFrame(animation);animation=null;}session=null;}
function renderLibrary(){stopRuntime();$('#arcadeTitle').textContent='Study Arcade';$('#arcadeBack').hidden=true;const content=$('#arcadeContent'),source=currentLesson();content.innerHTML=`<section class="arcade-collection-head"><span>YOUR TIER 3 MINI GAMES</span><h3>Choose a game</h3><p>Each activity uses words from the selected learning language and meanings from the selected known language.</p>${lessonSourceMarkup(source,{selectable:true})}</section><div class="arcade-library">${GAMES.filter(game=>owned(game.id)).map(game=>gameCard(game,'bag')).join('')||'<p class="arcade-empty">Unlock a mini game from the Shop first.</p>'}</div>`;bind(content,renderLibrary);}
function start(id){if(tier()<3||!owned(id)){close();return false;}stopRuntime();const game=GAMES.find(item=>item.id===id);if(!game)return false;$('#arcadeTitle').textContent=game.name;$('#arcadeBack').hidden=false;if(id==='memory')startMemory();else if(id==='matching')startMatching();else if(id==='shooter')startShooter();else if(id==='echo')startEcho();else if(id==='grammar')startGrammar();else if(id==='treasure')startTreasure();else if(id==='crystal-memory')startCrystalMemory();else if(id==='impostor')startImpostor();return true;}
function record(id,value){ensure();value=Number(value);if(!Number.isFinite(value))return;const old=Number(state.v6.arcadeBest[id]),hasOld=Number.isFinite(old);if(id==='memory'||id==='matching'||id==='crystal-memory'){if(!hasOld||value<old)state.v6.arcadeBest[id]=value;}else if(!hasOld||value>old)state.v6.arcadeBest[id]=value;save();}
function bestLabel(id,value){return id==='memory'||id==='crystal-memory'?`${value} moves`:id==='matching'?`${value}s`:`${value} points`;}
function recordRun(id,value,label,source){ensure();state.v6.arcadeHistory=Array.isArray(state.v6.arcadeHistory)?state.v6.arcadeHistory:[];state.v6.arcadeHistory.push({id,score:Number.isFinite(Number(value))?Number(value):0,result:String(label||''),difficulty:arcadeMode(),lesson:String(source?.label||currentLesson().label||''),completedAt:Date.now()});state.v6.arcadeHistory=state.v6.arcadeHistory.slice(-100);save();}
function finishView(id,title,detail,value,resultLabel=''){const completed=session,game=GAMES.find(item=>item.id===id),label=resultLabel||(Number.isFinite(Number(value))?bestLabel(id,value):'');if(Number.isFinite(Number(value)))record(id,value);recordRun(id,value,label,completed?.source);stopRuntime();$('#arcadeContent').innerHTML=`<section class="arcade-results"><span>${game.icon}</span><h3>${escape(title)}</h3><p>${escape(detail)}</p>${label?`<strong>${escape(label)}</strong>`:''}<div><button type="button" data-arcade-replay="${id}">Play again</button><button type="button" id="arcadeResultsLibrary">Choose another game</button></div></section>`;$('[data-arcade-replay]').onclick=()=>start(id);$('#arcadeResultsLibrary').onclick=renderLibrary;}
function startMemory(){const lesson=vocabularyPairs(6),pairs=lesson.pairs,cards=shuffle(pairs.flatMap(pair=>[{key:pair.id,type:'learn',text:pair.learn},{key:pair.id,type:'meaning',text:pair.meaning}]));session={id:'memory',source:lesson.source,pairs,cards,open:[],matched:new Set(),moves:0,locked:false};$('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>MEMORIZATION GAME</span><h3>Connect the word pairs</h3><p>Flip two cards. Match each learning word with its known-language meaning.</p></div><strong id="arcadeMemoryMoves">0 moves</strong></section>${lessonSourceMarkup(lesson.source,{selectable:true})}<div class="arcade-memory-grid" data-lm-no-interface-translate>${cards.map((card,index)=>`<button type="button" data-memory-card="${index}" data-memory-key="${escape(card.key)}" aria-label="Hidden memory card"><span class="arcade-memory-cover">⛏️</span><b class="arcade-memory-word" hidden>${escape(card.text)}</b></button>`).join('')}</div>`;bindGameLessonSelector('memory');document.querySelectorAll('[data-memory-card]').forEach(button=>button.onclick=()=>flipMemory(Number(button.dataset.memoryCard)));}
function setMemoryCardVisible(index,visible){const button=$(`[data-memory-card="${index}"]`);if(!button)return;button.classList.toggle('revealed',visible);const cover=button.querySelector('.arcade-memory-cover'),word=button.querySelector('.arcade-memory-word');if(cover)cover.hidden=visible;if(word)word.hidden=!visible;}
function flipMemory(index){const s=session;if(s?.id!=='memory'||s.locked||s.matched.has(s.cards[index].key)||s.open.includes(index))return;const button=$(`[data-memory-card="${index}"]`);setMemoryCardVisible(index,true);button.setAttribute('aria-label',s.cards[index].text);s.open.push(index);if(s.open.length<2)return;s.moves++;$('#arcadeMemoryMoves').textContent=`${s.moves} moves`;const [a,b]=s.open;if(s.cards[a].key===s.cards[b].key&&s.cards[a].type!==s.cards[b].type){s.matched.add(s.cards[a].key);[a,b].forEach(value=>$(`[data-memory-card="${value}"]`).classList.add('matched'));s.open=[];if(s.matched.size===s.pairs.length)setTimeout(()=>finishView('memory','Memory Mine cleared!',`You matched all ${s.pairs.length} word pairs in ${s.moves} moves.`,s.moves),350);return;}s.locked=true;setTimeout(()=>{[a,b].forEach(value=>setMemoryCardVisible(value,false));s.open=[];s.locked=false;},700);}
function startMatching(){const lesson=vocabularyPairs(8),pairs=lesson.pairs;session={id:'matching',source:lesson.source,pairs,left:null,right:null,matched:new Set(),score:0,time:60};$('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>MATCHING GAME</span><h3>Connect the word pairs</h3><p>Choose one tile from each column. You have 60 seconds.</p></div><strong id="arcadeMatchTimer">60s</strong></section>${lessonSourceMarkup(lesson.source,{selectable:true})}<div class="arcade-match-status" id="arcadeMatchStatus">Select a learning word.</div><div class="arcade-match-board" data-lm-no-interface-translate><div>${shuffle(pairs).map(pair=>`<button type="button" data-match-side="left" data-match-id="${pair.id}">${escape(pair.learn)}</button>`).join('')}</div><div>${shuffle(pairs).map(pair=>`<button type="button" data-match-side="right" data-match-id="${pair.id}">${escape(pair.meaning)}</button>`).join('')}</div></div>`;bindGameLessonSelector('matching');document.querySelectorAll('[data-match-side]').forEach(button=>button.onclick=()=>selectMatch(button));timer=setInterval(()=>{if(session?.id!=='matching')return;session.time--;$('#arcadeMatchTimer').textContent=`${session.time}s`;if(session.time<=0)finishView('matching','Time is up!',`You connected ${session.score} of ${session.pairs.length} pairs.`,null,`${session.score} matches`);},1000);}
function selectMatch(button){const s=session;if(s?.id!=='matching'||button.disabled)return;const side=button.dataset.matchSide;s[side]=button;document.querySelectorAll(`[data-match-side="${side}"]`).forEach(tile=>tile.classList.toggle('selected',tile===button));if(!s.left||!s.right)return;const correct=s.left.dataset.matchId===s.right.dataset.matchId;if(correct){const id=s.left.dataset.matchId;s.matched.add(id);s.score++;[s.left,s.right].forEach(tile=>{tile.disabled=true;tile.classList.add('matched');});$('#arcadeMatchStatus').textContent=`Correct — ${s.score}/${s.pairs.length} matched`;s.left=s.right=null;if(s.score===s.pairs.length){const elapsed=Math.max(1,60-s.time);finishView('matching','Crystal Match cleared!',`All ${s.pairs.length} pairs connected with ${s.time} seconds left.`,elapsed);}}else{const left=s.left,right=s.right;$('#arcadeMatchStatus').textContent='Try again — those words do not match.';[left,right].forEach(tile=>tile.classList.add('wrong'));s.left=s.right=null;setTimeout(()=>[left,right].forEach(tile=>tile.classList.remove('selected','wrong')),350);}}
function startShooter(){const lesson=vocabularyPairs(20),pairs=lesson.pairs;session={id:'shooter',source:lesson.source,pairs,index:0,score:0,time:45,ship:50,targets:[],last:performance.now(),running:true,keys:new Set(),waveResolved:false};$('#arcadeContent').innerHTML=`<section class="arcade-game-head arcade-shooter-head"><div><span>TIMED ALIGNMENT GAME</span><h3 id="arcadeShooterPrompt" data-lm-no-interface-translate>Loading word…</h3><p>Move the arrow beneath the matching meaning before the words reach the target line.</p></div><strong><b id="arcadeShooterScore">0</b> · <span id="arcadeShooterTimer">45s</span></strong></section>${lessonSourceMarkup(lesson.source,{selectable:true})}<div class="arcade-shooter-field" id="arcadeShooterField" tabindex="0" aria-label="Star Word Defender alignment field"><div class="arcade-starfield"></div><div class="arcade-alignment-line"><span>ALIGN HERE</span></div><div class="arcade-ship" id="arcadeShip">▲</div><div class="arcade-shooter-controls arcade-alignment-controls"><button type="button" data-ship-move="-1" aria-label="Move arrow left">◀</button><button type="button" data-ship-move="1" aria-label="Move arrow right">▶</button></div></div>`;bindGameLessonSelector('shooter');nextShooterWave();const field=$('#arcadeShooterField');field.focus();field.onkeydown=event=>{if(['ArrowLeft','ArrowRight'].includes(event.key))event.preventDefault();session?.keys.add(event.key);};field.onkeyup=event=>session?.keys.delete(event.key);document.querySelectorAll('[data-ship-move]').forEach(button=>button.onclick=()=>moveShip(Number(button.dataset.shipMove)*12));timer=setInterval(()=>{if(session?.id!=='shooter')return;session.time--;$('#arcadeShooterTimer').textContent=`${session.time}s`;if(session.time<=0)finishShooter();},1000);animation=requestAnimationFrame(shooterFrame);}
function nextShooterWave(){const s=session;if(s?.id!=='shooter')return;const pair=s.pairs[s.index%s.pairs.length],wrong=shuffle(s.pairs.filter(item=>item.id!==pair.id)).slice(0,3),positions=[14,38,62,86];s.current=pair;s.waveResolved=false;s.targets=shuffle([pair,...wrong]).map((item,index)=>({id:item.id,text:item.meaning,x:positions[index],y:-10-Math.random()*10,speed:.034,el:null}));s.index++;$('#arcadeShooterPrompt').textContent=`Align with: ${pair.learn}`;const field=$('#arcadeShooterField');field.querySelectorAll('.arcade-target').forEach(el=>el.remove());s.targets.forEach(target=>{const el=document.createElement('div');el.className='arcade-target';el.setAttribute('data-lm-no-interface-translate','');el.textContent=target.text;el.style.left=`${target.x}%`;target.el=el;field.appendChild(el);});}
function moveShip(delta){if(session?.id!=='shooter')return;session.ship=Math.max(6,Math.min(94,session.ship+delta));$('#arcadeShip').style.left=`${session.ship}%`;}
function resolveShooterAlignment(){const s=session;if(s?.id!=='shooter'||s.waveResolved)return;s.waveResolved=true;const aligned=s.targets.reduce((best,target)=>Math.abs(target.x-s.ship)<Math.abs(best.x-s.ship)?target:best,s.targets[0]),correct=aligned?.id===s.current.id;if(correct)s.score+=1;$('#arcadeShooterScore').textContent=s.score;aligned?.el?.classList.add(correct?'aligned-correct':'aligned-wrong');s.targets.forEach(target=>{if(target!==aligned)target.el?.classList.add('not-aligned');});setTimeout(()=>{if(session!==s||s.id!=='shooter'||!s.running)return;s.targets.forEach(target=>target.el?.remove());s.targets=[];nextShooterWave();},280);}
function shooterFrame(now){const s=session;if(s?.id!=='shooter'||!s.running)return;const delta=Math.min(40,now-s.last);s.last=now;if(s.keys.has('ArrowLeft'))moveShip(-delta*.07);if(s.keys.has('ArrowRight'))moveShip(delta*.07);for(const target of s.targets){target.y+=target.speed*delta;target.el.style.top=`${target.y}%`;}if(!s.waveResolved&&s.targets.some(target=>target.y>=68))resolveShooterAlignment();animation=requestAnimationFrame(shooterFrame);}
function finishShooter(){if(session?.id!=='shooter')return;session.running=false;const score=session.score;finishView('shooter','Defense shift complete!',`You defended the mine for 45 seconds and scored ${score} points.`,score);}
function startEcho(){
 const lesson=vocabularyPairs(16),mode=arcadeMode(),extra=courseItems('vocabulary').map(item=>({id:`course-${item.id}`,learn:item.learn,meaning:item.meaning})),pool=[...lesson.pairs];
 extra.forEach(pair=>{if(!pool.some(item=>item.learn===pair.learn))pool.push(pair);});const roundCount=mode==='hard'?10:8,rounds=repeatPairs(lesson.pairs.length?lesson.pairs:pool,roundCount);
 session={id:'echo',source:lesson.source,pairs:pool,rounds,index:0,score:0,answered:false};
 $('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>LISTENING CHALLENGE</span><h3>Hear the cavern echo</h3><p>${mode==='hard'?'Natural-speed audio plays once. Choose carefully.':'Replay the slower audio whenever you need it.'}</p></div><strong id="arcadeEchoScore">0 / ${roundCount}</strong></section>${modeMarkup('echo')}${lessonSourceMarkup(lesson.source,{selectable:true})}<section class="arcade-echo-stage" data-lm-no-interface-translate><div class="arcade-echo-rings" aria-hidden="true">◖ ))) ◗</div><span id="arcadeEchoRound"></span><h3>What did you hear?</h3><button id="arcadeEchoReplay" class="arcade-audio-button" type="button">🔊 ${mode==='hard'?'Play audio':'Hear again'}</button><div id="arcadeEchoChoices" class="arcade-choice-grid"></div><p id="arcadeLiveStatus" class="arcade-feedback" aria-live="polite"></p></section>`;
 bindMode('echo');bindGameLessonSelector('echo');$('#arcadeEchoReplay').onclick=()=>playEchoAudio();renderEchoRound();
}
function renderEchoRound(){const s=session;if(s?.id!=='echo')return;if(s.index>=s.rounds.length){finishView('echo','Echo Cavern mastered!',`You identified ${s.score} of ${s.rounds.length} spoken clues.`,s.score);return;}s.answered=false;s.current=s.rounds[s.index];const alternatives=shuffle(s.pairs.filter(pair=>pair.id!==s.current.id&&pair.meaning!==s.current.meaning)).slice(0,3),choices=shuffle([s.current,...alternatives]);$('#arcadeEchoRound').textContent=`Echo ${s.index+1} of ${s.rounds.length}`;$('#arcadeEchoChoices').innerHTML=choices.map(pair=>`<button type="button" data-echo-choice="${escape(pair.id)}">${escape(pair.meaning)}</button>`).join('');$('#arcadeLiveStatus').textContent='Listen, then choose the matching meaning.';document.querySelectorAll('[data-echo-choice]').forEach(button=>button.onclick=()=>answerEcho(button));timer=setTimeout(()=>playEchoAudio(),160);}
function playEchoAudio(){const s=session;if(s?.id!=='echo'||!s.current)return;speakArcade(s.current.learn,s.source.learning,arcadeMode()==='hard'?1.03:.82);}
function answerEcho(button){const s=session;if(s?.id!=='echo'||s.answered)return;s.answered=true;const correct=button.dataset.echoChoice===String(s.current.id);if(correct)s.score++;document.querySelectorAll('[data-echo-choice]').forEach(choice=>{choice.disabled=true;if(choice.dataset.echoChoice===String(s.current.id))choice.classList.add('matched');});if(!correct)button.classList.add('wrong');$('#arcadeEchoScore').textContent=`${s.score} / ${s.rounds.length}`;notifyArcade(correct,`${correct?'Correct!':'Not quite.'} ${s.current.learn} means ${s.current.meaning}.`);s.index++;timer=setTimeout(renderEchoRound,850);}
function startGrammar(){
 const bank=shuffle(sentenceBank()),mode=arcadeMode(),roundCount=Math.min(bank.length,mode==='hard'?7:5),source=currentLesson();session={id:'grammar',source,rounds:bank.slice(0,roundCount),index:0,score:0,chosen:[],attempts:0};
 $('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>SENTENCE BUILDING GAME</span><h3>Forge the sentence</h3><p>${mode==='hard'?'Arrange the sentence without a word-order hint and ignore the extra pieces.':'Tap each word in the correct order. You can undo or clear your forge.'}</p></div><strong id="arcadeGrammarScore">0 / ${roundCount}</strong></section>${modeMarkup('grammar')}${lessonSourceMarkup(source)}<section class="arcade-grammar-forge" data-lm-no-interface-translate><span id="arcadeGrammarRound"></span><p id="arcadeGrammarMeaning"></p><div id="arcadeGrammarAnswer" class="arcade-forge-answer" aria-label="Your sentence"></div><div id="arcadeGrammarTokens" class="arcade-token-bank"></div><div class="arcade-forge-actions"><button id="arcadeGrammarUndo" type="button">↶ Undo</button><button id="arcadeGrammarClear" type="button">Clear</button><button id="arcadeGrammarSubmit" class="primary" type="button">⚒️ Test sentence</button></div><p id="arcadeLiveStatus" class="arcade-feedback" aria-live="polite"></p></section>`;
 bindMode('grammar');$('#arcadeGrammarUndo').onclick=undoGrammar;$('#arcadeGrammarClear').onclick=clearGrammar;$('#arcadeGrammarSubmit').onclick=submitGrammar;renderGrammarRound();
}
function renderGrammarRound(){const s=session;if(s?.id!=='grammar')return;if(s.index>=s.rounds.length){finishView('grammar','Grammar Forge complete!',`You forged ${s.score} of ${s.rounds.length} sentences.`,s.score);return;}s.current=s.rounds[s.index];s.chosen=[];s.attempts=0;const base=s.current.tokens.map((text,index)=>({key:`target-${index}`,text})),distractors=arcadeMode()==='hard'?shuffle(s.rounds[(s.index+1)%s.rounds.length]?.tokens||[]).filter(text=>!s.current.tokens.includes(text)).slice(0,2).map((text,index)=>({key:`extra-${index}`,text})):[];s.tokens=shuffle([...base,...distractors]);$('#arcadeGrammarRound').textContent=`Sentence ${s.index+1} of ${s.rounds.length}`;$('#arcadeGrammarMeaning').textContent=s.current.meaning;$('#arcadeGrammarTokens').innerHTML=s.tokens.map(token=>`<button type="button" data-grammar-token="${token.key}">${escape(token.text)}</button>`).join('');document.querySelectorAll('[data-grammar-token]').forEach(button=>button.onclick=()=>chooseGrammarToken(button));renderGrammarAnswer();}
function chooseGrammarToken(button){const s=session;if(s?.id!=='grammar'||button.disabled)return;const token=s.tokens.find(item=>item.key===button.dataset.grammarToken);if(!token)return;s.chosen.push(token);button.disabled=true;button.classList.add('selected');renderGrammarAnswer();}
function renderGrammarAnswer(){const s=session;if(s?.id!=='grammar')return;$('#arcadeGrammarAnswer').innerHTML=s.chosen.length?s.chosen.map(token=>`<span>${escape(token.text)}</span>`).join(''):'<em>Tap language pieces to build the sentence.</em>';$('#arcadeGrammarSubmit').disabled=!s.chosen.length;}
function undoGrammar(){const s=session;if(s?.id!=='grammar'||!s.chosen.length)return;const token=s.chosen.pop(),button=$(`[data-grammar-token="${token.key}"]`);if(button){button.disabled=false;button.classList.remove('selected');}renderGrammarAnswer();}
function clearGrammar(){const s=session;if(s?.id!=='grammar')return;s.chosen=[];document.querySelectorAll('[data-grammar-token]').forEach(button=>{button.disabled=false;button.classList.remove('selected');});renderGrammarAnswer();}
function submitGrammar(){const s=session;if(s?.id!=='grammar'||!s.chosen.length)return;const answer=s.chosen.map(token=>token.text).join('\u241f'),target=s.current.tokens.join('\u241f'),correct=answer===target,status=$('#arcadeGrammarAnswer');if(correct){s.score++;status.classList.add('matched');document.querySelectorAll('[data-grammar-token]').forEach(button=>button.disabled=true);$('#arcadeGrammarScore').textContent=`${s.score} / ${s.rounds.length}`;notifyArcade(true,`Sentence forged: ${s.current.learn}`);s.index++;timer=setTimeout(()=>{status.classList.remove('matched');renderGrammarRound();},850);}else{s.attempts++;status.classList.add('wrong');notifyArcade(false,'The pieces are not in the correct order yet. Try the forge again.');timer=setTimeout(()=>{status.classList.remove('wrong');clearGrammar();},700);}}
function directionForms(){const {learning,known}=languageSettings(),data=window.LANGUAGE_MINER_MULTILINGUAL_COURSE_DATA?.vocabulary||[],details={up:[17,0,-1,'↑'],right:[24,1,0,'→'],down:[18,0,1,'↓'],left:[23,-1,0,'←']};return Object.entries(details).map(([id,[wordId,dx,dy,icon]])=>{const item=data.find(entry=>Number(entry.id)===wordId);return {id,dx,dy,icon,learn:String(item?.forms?.[learning]||id),meaning:String(item?.forms?.[known]||id)};});}
function treasurePath(count,directions){let x=2,y=2,path=[];for(let step=0;step<count;step++){const valid=directions.filter(direction=>x+direction.dx>=0&&x+direction.dx<5&&y+direction.dy>=0&&y+direction.dy<5),chosen=shuffle(valid)[0];path.push(chosen);x+=chosen.dx;y+=chosen.dy;}return {path,target:{x,y}};}
function startTreasure(){const source=currentLesson(),mode=arcadeMode(),directions=directionForms(),route=treasurePath(mode==='hard'?8:6,directions);session={id:'treasure',source,directions,path:route.path,target:route.target,position:{x:2,y:2},index:0,score:0,mistakes:0};$('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>DIRECTION TRANSLATION GAME</span><h3>Follow the buried clues</h3><p>${mode==='hard'?'Translate each clue without labeled arrows.':'Direction buttons include known-language support.'}</p></div><strong id="arcadeTreasureScore">0 / ${route.path.length}</strong></section>${modeMarkup('treasure')}${lessonSourceMarkup(source)}<section class="arcade-treasure-game" data-lm-no-interface-translate><div id="arcadeTreasureMap" class="arcade-treasure-map"></div><div class="arcade-treasure-clue"><span id="arcadeTreasureRound"></span><h3 id="arcadeTreasureWord"></h3><p>Which direction does this clue mean?</p><div class="arcade-direction-pad">${directions.map(direction=>`<button type="button" data-treasure-direction="${direction.id}"><b>${direction.icon}</b>${mode==='easy'?`<span>${escape(direction.meaning)}</span>`:''}</button>`).join('')}</div><p id="arcadeLiveStatus" class="arcade-feedback" aria-live="polite"></p></div></section>`;bindMode('treasure');document.querySelectorAll('[data-treasure-direction]').forEach(button=>button.onclick=()=>answerTreasure(button));renderTreasureRound();}
function renderTreasureMap(){const s=session;if(s?.id!=='treasure')return;const cells=[];for(let y=0;y<5;y++)for(let x=0;x<5;x++){const player=x===s.position.x&&y===s.position.y,target=x===s.target.x&&y===s.target.y;cells.push(`<span class="${player?'player ':''}${target?'treasure ':''}">${player?'🧑‍🏭':target&&arcadeMode()==='easy'?'✨':'·'}</span>`);}$('#arcadeTreasureMap').innerHTML=cells.join('');}
function renderTreasureRound(){const s=session;if(s?.id!=='treasure')return;renderTreasureMap();if(s.index>=s.path.length){finishView('treasure','Treasure uncovered!',`You translated the route with ${s.mistakes} wrong turn${s.mistakes===1?'':'s'}.`,s.score);return;}const clue=s.path[s.index];$('#arcadeTreasureRound').textContent=`Clue ${s.index+1} of ${s.path.length}`;$('#arcadeTreasureWord').textContent=clue.learn;$('#arcadeLiveStatus').textContent='Translate the clue to move your miner.';}
function answerTreasure(button){const s=session;if(s?.id!=='treasure')return;const clue=s.path[s.index],chosen=s.directions.find(direction=>direction.id===button.dataset.treasureDirection),correct=chosen?.id===clue.id;document.querySelectorAll('[data-treasure-direction]').forEach(choice=>choice.disabled=true);if(correct){button.classList.add('matched');s.position.x+=clue.dx;s.position.y+=clue.dy;s.score++;s.index++;$('#arcadeTreasureScore').textContent=`${s.score} / ${s.path.length}`;notifyArcade(true,`${clue.learn} means ${clue.meaning}. Moving ${clue.meaning}.`);}else{button.classList.add('wrong');s.mistakes++;notifyArcade(false,`${chosen?.learn||''} is not this clue. Look for ${clue.meaning}.`);}timer=setTimeout(()=>{document.querySelectorAll('[data-treasure-direction]').forEach(choice=>{choice.disabled=false;choice.classList.remove('matched','wrong');});renderTreasureRound();},correct?650:800);}
function startCrystalMemory(){const lesson=vocabularyPairs(arcadeMode()==='hard'?5:4),pairs=lesson.pairs.slice(0,arcadeMode()==='hard'?5:4),cards=shuffle(pairs.flatMap(pair=>[{key:pair.id,type:'learn',text:pair.learn},{key:pair.id,type:'meaning',text:pair.meaning},{key:pair.id,type:'audio',text:'🔊 Hear'}]));session={id:'crystal-memory',source:lesson.source,pairs,cards,open:[],matched:new Set(),moves:0,locked:false};$('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>THREE-WAY MEMORY GAME</span><h3>Connect crystal trios</h3><p>Match each learning word with its meaning and spoken-audio crystal.</p></div><strong id="arcadeCrystalMoves">0 moves</strong></section>${modeMarkup('crystal-memory')}${lessonSourceMarkup(lesson.source,{selectable:true})}<div class="arcade-crystal-memory-grid" data-lm-no-interface-translate>${cards.map((card,index)=>`<button type="button" data-crystal-card="${index}" aria-label="Hidden crystal card"><span class="arcade-crystal-cover">💎</span><b class="arcade-crystal-word" hidden>${escape(card.text)}</b></button>`).join('')}</div><p id="arcadeLiveStatus" class="arcade-feedback" aria-live="polite">Find three crystals from the same word family.</p>`;bindMode('crystal-memory');bindGameLessonSelector('crystal-memory');document.querySelectorAll('[data-crystal-card]').forEach(button=>button.onclick=()=>flipCrystalMemory(Number(button.dataset.crystalCard)));}
function setCrystalVisible(index,visible){const s=session,button=$(`[data-crystal-card="${index}"]`);if(!button||s?.id!=='crystal-memory')return;button.classList.toggle('revealed',visible);const cover=button.querySelector('.arcade-crystal-cover'),word=button.querySelector('.arcade-crystal-word');if(cover)cover.hidden=visible;if(word)word.hidden=!visible;}
function flipCrystalMemory(index){const s=session;if(s?.id!=='crystal-memory'||s.locked||s.matched.has(s.cards[index].key)||s.open.includes(index))return;const card=s.cards[index],button=$(`[data-crystal-card="${index}"]`);setCrystalVisible(index,true);button.setAttribute('aria-label',card.type==='audio'?'Play pronunciation':card.text);if(card.type==='audio')speakArcade(s.pairs.find(pair=>pair.id===card.key)?.learn,s.source.learning,.9);s.open.push(index);if(s.open.length<3)return;s.moves++;$('#arcadeCrystalMoves').textContent=`${s.moves} moves`;const selected=s.open.map(value=>s.cards[value]),matched=selected.every(item=>item.key===selected[0].key)&&new Set(selected.map(item=>item.type)).size===3;if(matched){s.matched.add(selected[0].key);s.open.forEach(value=>$(`[data-crystal-card="${value}"]`).classList.add('matched'));s.open=[];notifyArcade(true,'Crystal trio matched!');if(s.matched.size===s.pairs.length)timer=setTimeout(()=>finishView('crystal-memory','Crystal Memory Match cleared!',`You connected ${s.pairs.length} word, meaning, and audio trios in ${s.moves} moves.`,s.moves),400);}else{s.locked=true;s.open.forEach(value=>$(`[data-crystal-card="${value}"]`).classList.add('wrong'));notifyArcade(false,'Those three crystals belong to different word families.');timer=setTimeout(()=>{s.open.forEach(value=>{setCrystalVisible(value,false);$(`[data-crystal-card="${value}"]`).classList.remove('wrong');});s.open=[];s.locked=false;},800);}}
function impostorGroups(){const vocabulary=courseItems('vocabulary'),byId=new Map(vocabulary.map(item=>[Number(item.id),item]));return IMPOSTOR_GROUPS.map(group=>({...group,items:group.ids.map(id=>byId.get(id)).filter(Boolean)})).filter(group=>group.items.length>=4);}
function startImpostor(){const source=currentLesson(),groups=impostorGroups(),roundCount=arcadeMode()==='hard'?10:8;session={id:'impostor',source,groups,index:0,roundCount,score:0};$('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>VOCABULARY CATEGORY GAME</span><h3>Expose the impostor</h3><p>${arcadeMode()==='hard'?'Five words appear each round with no translation hints.':'Four words appear each round. Meanings are explained after every answer.'}</p></div><strong id="arcadeImpostorScore">0 / ${roundCount}</strong></section>${modeMarkup('impostor')}${lessonSourceMarkup(source)}<section class="arcade-impostor-game" data-lm-no-interface-translate><span id="arcadeImpostorRound"></span><h3 id="arcadeImpostorPrompt"></h3><div id="arcadeImpostorChoices" class="arcade-impostor-choices"></div><p id="arcadeLiveStatus" class="arcade-feedback" aria-live="polite"></p></section>`;bindMode('impostor');renderImpostorRound();}
function renderImpostorRound(){const s=session;if(s?.id!=='impostor')return;if(s.index>=s.roundCount){finishView('impostor','Impostor investigation complete!',`You exposed ${s.score} of ${s.roundCount} impostor words.`,s.score);return;}const target=shuffle(s.groups)[0],other=shuffle(s.groups.filter(group=>group.id!==target.id))[0],regularCount=arcadeMode()==='hard'?4:3,regular=shuffle(target.items).slice(0,regularCount),outsider=shuffle(other.items)[0];s.current={target,other,outsider,choices:shuffle([...regular,outsider])};$('#arcadeImpostorRound').textContent=`Case ${s.index+1} of ${s.roundCount}`;$('#arcadeImpostorPrompt').textContent=`Which word does not belong with: ${target.label}?`;$('#arcadeImpostorChoices').innerHTML=s.current.choices.map(item=>`<button type="button" data-impostor-choice="${escape(item.id)}">${escape(item.learn)}</button>`).join('');$('#arcadeLiveStatus').textContent='Choose the unrelated word.';document.querySelectorAll('[data-impostor-choice]').forEach(button=>button.onclick=()=>answerImpostor(button));}
function answerImpostor(button){const s=session;if(s?.id!=='impostor')return;const chosen=s.current.choices.find(item=>String(item.id)===button.dataset.impostorChoice),correct=chosen===s.current.outsider;if(correct)s.score++;document.querySelectorAll('[data-impostor-choice]').forEach(choice=>{choice.disabled=true;if(choice.dataset.impostorChoice===String(s.current.outsider.id))choice.classList.add('matched');});if(!correct)button.classList.add('wrong');$('#arcadeImpostorScore').textContent=`${s.score} / ${s.roundCount}`;notifyArcade(correct,`${s.current.outsider.learn} means ${s.current.outsider.meaning}. It belongs with ${s.current.other.label}, not ${s.current.target.label}.`);s.index++;timer=setTimeout(renderImpostorRound,1000);}
function closeOtherOverlays(){document.getElementById('closeShopBtn')?.click();document.getElementById('utilityClose')?.click();window.syncJapaneseMinerPageScroll?.();}
window.LanguageMinerArcade=Object.freeze({games:()=>GAMES.map(game=>({...game,owned:owned(game.id)})),owned,claim,shopMarkup,bagMarkup,bind,open,close,currentLesson:()=>{const source=currentLesson();return {...source,pairs:source.pairs.map(pair=>({...pair}))};},lessonOptions:()=>lessonOptions().map(option=>({...option})),selectLesson});
window.addEventListener('jm-supporter-entitlement-changed',()=>{if($('#arcadeOverlay')?.classList.contains('open')&&tier()<3)close();});
})();
