/* Daily Mini Golem — free, account-wide, separate from learning streaks and Patreon. */
(()=>{'use strict';
 const M=window.LanguageMinerDailyGolemModel;
 let anchor=null,busy=false,syncing=false,notice='',lastSignature='',seen=new WeakSet(),pending=[];
 const profile=()=>window.japaneseMinerActiveProfile?.();
 const identity=()=>profile()?.cloudUserId||'';
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const t=s=>window.LanguageMinerDailyGolemText?.(s)||s;
 function day(){if(!anchor||anchor.user!==identity()||performance.now()-anchor.at>300000)return '';return new Date(anchor.time+performance.now()-anchor.at).toISOString().slice(0,10);}
 function record(){return M.roll(state.dailyGolem,day());}
 function rewardText(reward){return [reward.nuggets?`${reward.nuggets.toLocaleString()} ${t('Nuggets')}`:'',reward.hints?`${t('Hints')} ×${reward.hints}`:'',reward.shields?`${t('Shields')} ×${reward.shields}`:'',reward.cosmetic?`${t('Daily Miner')} +1/4`:''].filter(Boolean).join(' · ');}
 function art(r){const track=r.claims%7+1,cracks=['M59 21 53 40 64 48','M53 40 38 49 42 66','M64 48 77 62 70 75','M42 66 51 78 45 92','M70 75 61 88 69 104'];return `<svg class="dg-stone" viewBox="0 0 120 130" aria-hidden="true" data-tier="${track}"><ellipse cx="60" cy="119" rx="43" ry="7" fill="#071824" opacity=".3"/><g class="dg-shell"><path fill="#789294" stroke="#304e60" stroke-width="3" d="M25 104 19 73 26 40 43 18 72 15 92 35 101 71 94 105 73 115 43 115Z"/><path fill="#a6bdb7" d="M26 40 43 18 72 15 60 43 34 69Z"/><path fill="#4c6b78" d="M60 43 92 35 101 71 94 105 72 93Z"/><g class="dg-eyes" fill="#e5fcbb"><ellipse cx="44" cy="61" rx="6" ry="7"/><ellipse cx="75" cy="61" rx="6" ry="7"/></g><path d="M51 76 Q60 83 68 76" fill="none" stroke="#d8ead3" stroke-width="3"/>${Array.from({length:track-1},(_,i)=>`<path class="dg-crystal" fill="hsl(${track===7?i*60:160+track*13} 75% 73%)" d="m${22+i*14} ${40-(i%2)*10} -5 -19 7 -12 8 17 -3 14Z"/>`).join('')}${cracks.slice(0,r.questions).map(d=>`<path d="${d}" fill="none" stroke="#e0ffaf" stroke-width="3"/>`).join('')}</g></svg>`;}
 function mount(){let box=document.getElementById('dailyGolem');if(box)return box;const host=document.getElementById('challengeArea')?.parentElement;if(!host)return null;box=document.createElement('section');box.id='dailyGolem';box.className='daily-golem';box.setAttribute('aria-label',t('Daily Mini Golem'));host.after(box);return box;}
 function draw(){const box=mount();if(!box)return;box.hidden=!profile();if(box.hidden){document.querySelector('.dg-equipped-title')?.remove();return;}const r=record(),claimed=!!day()&&r.lastClaim===day(),track=claimed?(r.claims-1)%7+1:r.claims%7+1,ready=!!day()&&r.questions===5&&!claimed;const signature=JSON.stringify([r,day(),busy,notice,identity(),window.LanguageMinerI18n?.getLocale()]);if(signature===lastSignature)return;lastSignature=signature;document.querySelector('.dg-equipped-title')?.remove();if(r.titleEquipped&&r.weeks>=4){const badge=document.createElement('span');badge.className='dg-equipped-title dg-badge';badge.textContent='✦ '+t('Daily Miner');document.querySelector('.adventure-avatar')?.append(badge);}
 box.innerHTML=`<div class="dg-art">${art({...r,claims:track-1})}</div><div class="dg-info"><small>${esc(t('Daily Reward'))} · ${esc(t('Day'))} ${track}/7</small><h3>${esc(t(track===7?'Prismatic Mini Golem':'Daily Mini Golem'))}</h3><p>${esc(rewardText(M.rewards[track-1]))}</p><div class="dg-progress" role="progressbar" aria-label="${esc(t('Practice questions'))}" aria-valuemin="0" aria-valuemax="5" aria-valuenow="${r.questions}">${Array.from({length:5},(_,i)=>`<i class="${i<r.questions?'done':''}"></i>`).join('')}</div><p>${esc(t('Practice questions'))} ${r.questions}/5</p><p class="dg-status" role="status">${esc(notice||(!identity()?t('Sign in to save daily rewards'):!day()?t('Connect to sync your daily golem'):claimed?t('Reward claimed today'):ready?t('READY TO BREAK'):''))}</p><button type="button" class="dg-break" ${busy||syncing||claimed||!identity()?'disabled':''}>${esc(t(claimed?'Reward claimed today':ready?'Break Golem':day()?'Practice 5 questions':'Sync daily reward'))}</button><details><summary>${esc(t('7-day rewards'))}</summary><ol>${M.rewards.map((x,i)=>`<li>${esc(t('Day'))} ${i+1}: ${esc(rewardText(x))}</li>`).join('')}</ol><p>${esc(t('Missed days keep your reward day. Questions reset at 00:00 UTC.'))}</p><p>${esc(t('Daily Miner'))}: ${Math.min(4,r.weeks)}/4 · ${esc(t('Weekly cores unlock a free title.'))}</p></details>${r.weeks>=4?`<button type="button" class="dg-title">${esc(t(r.titleEquipped?'Remove':'Equip')+' '+t('Daily Miner'))}</button>`:''}${r.titleEquipped?`<strong class="dg-badge">✦ ${esc(t('Daily Miner'))} ✦</strong>`:''}</div>`;
 box.querySelector('.dg-break').onclick=()=>{if(ready)breakGolem();else if(!day())sync();else{document.getElementById('rock')?.focus();document.getElementById('challengeArea')?.scrollIntoView({block:'center',behavior:'smooth'});}};
 box.querySelector('.dg-title')?.addEventListener('click',()=>{state.dailyGolem={...record(),titleEquipped:!record().titleEquipped};save();draw();});
 }
 async function sync(){if(syncing||busy||!identity())return;syncing=true;notice='';draw();try{const result=await window.languageMinerPushCloudSave?.();if(!result)throw Error('offline');}catch{notice=t('Connect to sync your daily golem');}finally{syncing=false;lastSignature='';draw();}}
 function cloudClock(event){const time=Date.parse(event.detail?.updatedAt);if(!Number.isFinite(time)||event.detail?.user!==identity())return;anchor={time,at:performance.now(),user:identity()};state.dailyGolem=M.roll(state.dailyGolem,day());const queued=pending;pending=[];for(const item of queued)if(item.user===identity()&&performance.now()-item.at<30000)practice(item.question);draw();}
 function practice(question){if(!question||typeof question!=='object'||seen.has(question)||question._dailyGolemCountedDay===day())return;if(!day()){if(identity()&&!pending.some(item=>item.question===question)&&pending.length<5)pending.push({question,user:identity(),at:performance.now()});sync();return;}seen.add(question);question._dailyGolemCountedDay=day();state.dailyGolem=M.practice(state.dailyGolem,day());save();draw();}
 async function breakGolem(){if(busy||!day())return;busy=true;notice='';draw();const user=identity(),expectedDay=day();const dialog=document.createElement('dialog');dialog.className='dg-dialog';dialog.setAttribute('aria-labelledby','dgDialogTitle');const r=record();dialog.innerHTML=`<h2 id="dgDialogTitle">${esc(t('Golem Core'))}</h2><div class="dg-scene" data-phase="wake"><div class="dg-player">${window.japaneseMinerCharacterMarkup?.('large')||''}<span class="dg-tool">${window.LanguageMinerPickaxeFinishes?.preview(activePickaxeSkin().id)||'⛏️'}</span><span class="dg-raised-arm" aria-hidden="true"></span><span class="dg-core"><svg viewBox="0 0 60 70" aria-hidden="true"><path fill="currentColor" stroke="#f5ffec" stroke-width="2" d="M30 2 54 20 50 49 30 67 10 49 6 20Z"/><path fill="#ffffff88" d="m30 2 -9 24 9 41 9-41Z"/><path fill="none" stroke="#fff9" d="M6 20 21 26 10 49M54 20 39 26 50 49"/></svg></span></div><div class="dg-egg">${art(r)}</div><span class="dg-sparkles">✧ ✦ ✧</span></div><p class="dg-reveal" role="status">${esc(t('The golem wakes up!'))}</p><button type="button" class="dg-skip">${esc(t('Skip animation'))}</button>`;document.body.append(dialog);dialog.showModal();dialog.addEventListener('cancel',e=>e.preventDefault());let skipped=false;dialog.querySelector('.dg-skip').onclick=()=>skipped=true;
 const scene=dialog.querySelector('.dg-scene'),reveal=dialog.querySelector('.dg-reveal');scene.classList.toggle('prismatic',r.claims%7===6);const shell=scene.querySelector('.dg-shell'),half=shell.cloneNode(true);shell.classList.add('dg-left');half.classList.add('dg-right');shell.after(half);dialog.querySelectorAll('.miner-avatar').forEach(a=>window.syncJapaneseMinerRenderedLayers?.(a));
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches||state.v6?.characterAnimations===false||state.v6?.reducedMotion===true||document.body.classList.contains('reduce-motion');
 const wait=ms=>new Promise(resolve=>{if(reduced||skipped)return resolve();let elapsed=0;const timer=setInterval(()=>{elapsed+=50;if(skipped||elapsed>=ms){clearInterval(timer);resolve();}},50);});
 try{await wait(650);scene.dataset.phase='strike';await wait(750);scene.dataset.phase='crack';await wait(700);scene.dataset.phase='victory';reveal.textContent=t('Golem Core');await wait(r.claims%7===6?1400:1000);const reward=M.rewards[r.claims%7];reveal.textContent=rewardText(reward);scene.dataset.phase='reward';await wait(600);if(user!==identity())throw Error('account changed');const result=await window.languageMinerCommitDailyGolem(expectedDay);if(!result)throw Error('not committed');reveal.textContent=`${t('Reward added')} · ${rewardText(result)}`;notice=t('Reward claimed today');}catch{reveal.textContent=t('Reward not confirmed. Sync before trying again.');notice=reveal.textContent;anchor=null;}finally{const close=dialog.querySelector('.dg-skip');close.textContent=t('Continue');close.onclick=()=>{dialog.close();dialog.remove();document.querySelector('#dailyGolem .dg-break')?.focus();};dialog.addEventListener('cancel',()=>{dialog.close();dialog.remove();},{once:true});busy=false;draw();close.focus();}
 }
 window.LanguageMinerDailyGolem=Object.freeze({practice,sync,refresh:draw});
 window.addEventListener('lm-cloud-save-clock',cloudClock);
 for(const name of ['jm-profile-loaded','jm-profile-logged-out','lm-cloud-session-changed'])window.addEventListener(name,()=>{anchor=null;seen=new WeakSet();pending=[];lastSignature='';draw();sync();});
 window.addEventListener('lm-interface-language-changed',()=>{lastSignature='';draw();});
 window.addEventListener('online',sync);window.addEventListener('lm-player-progress-saved',draw);
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync();});
 setInterval(()=>{draw();if(!day())sync();},30000);draw();sync();
})();


