/* Item-linked flashcard practice. Callers own unlock checks and mastery persistence. */
(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=items=>{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
let session=null,focusBefore=null;
const dialog=document.createElement('dialog');dialog.id='lmFlashcard';dialog.setAttribute('aria-labelledby','lmFlashcardHeading');
function normalize(item,language,known){const japaneseReading=language==='ja'?(window.N5_VOCABULARY_1000||[]).find(row=>row[0]===(item.forms?.ja||item.jp))?.[1]:'';const picture=window.LanguageMinerPictures?.imageFor(item,{language});return {...item,term:String(item.symbol||item.forms?.[language]||item.jp||''),meaning:String(picture?.answerName||item.name||item.forms?.[known]||item.en||''),speech:String(picture?.targetSpeech||item.spoken||item.reading||japaneseReading||item.symbol||item.forms?.[language]||item.jp||'')}}
function cancelAudio(){window.LanguageMinerSpeech?.cancel();window.speechSynthesis?.cancel()}
function hasAudio(text){return Boolean(window.LanguageMinerPronunciation?.lookup(text,session?.language,window.LanguageMinerSpeech?.gender()||'female')||voice())}
function voice(){const prefix=session?.language;return window.speechSynthesis?.getVoices().find(v=>v.lang.toLowerCase().split('-')[0]===prefix)}
function speak(text){const utteranceText=typeof text==='string'?text:session.items[session.index].speech;if(window.LanguageMinerSpeech){const played=window.LanguageMinerSpeech.replay(utteranceText,session.language);if(!played)dialog.querySelector('[data-fc-status]').textContent='Pronunciation is unavailable for this item. You can continue in Word mode.';return}const v=voice();if(!v)return;cancelAudio();const utterance=new SpeechSynthesisUtterance(utteranceText);utterance.voice=v;utterance.lang=v.lang;utterance.rate=.8;speechSynthesis.speak(utterance)}
function writtenKey(item){return item.term.normalize('NFKC').trim().replace(/^~+|~+$/g,'')}
function soundKey(item,language){let value=item.speech.normalize('NFKC').trim().replace(/^~+|~+$/g,'');if(language==='ja')value=value.replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60)).replace(/ぢ/g,'じ').replace(/づ/g,'ず').replace(/^を$/,'お');return value}
function pictureSenses(item){return String(item.forms?.en||item.en||'').toLowerCase().replace(/\([^)]*\)/g,'').split(/[,;/]/).map(x=>x.trim().replace(/^(?:to |a |an |the )/,'').trim()).filter(Boolean)}
function sharesPictureSense(a,b){const senses=new Set(pictureSenses(a));return pictureSenses(b).some(s=>senses.has(s))}
function render(){const s=session,item=s.items[s.index],art=window.LanguageMinerPictures?.imageFor(item,{language:s.language}),hasVoice=hasAudio(item.speech);if(s.mode==='picture'&&!art)s.mode='word';if(s.mode==='listen'&&!hasVoice)s.mode='word';const key=s.mode==='word'?'meaning':'term',answer=item[key],values=[...new Set(s.items.filter(i=>writtenKey(i)!==writtenKey(item)).filter(i=>s.mode!=='picture'||item.symbol||!sharesPictureSense(item,i)).filter(i=>!art?.pinyinType||window.LanguageMinerPictures?.imageFor(i,{language:s.language})?.pinyinType===art.pinyinType).filter(i=>s.mode==='picture'?((other)=>!other||(item.symbol?(other.concept||other.file)!==(art.concept||art.file):(other.file!==art.file&&(other.concept||other.file)!==(art.concept||art.file))))(window.LanguageMinerPictures?.imageFor(i,{language:s.language})):s.mode==='listen'?soundKey(i,s.language)!==soundKey(item,s.language):i.term!==item.term).map(i=>i[key]).filter(v=>v&&v!==answer))];s.options=shuffle([answer,...shuffle(values).slice(0,3)]);s.answer=answer;s.answered=false;const showArt=Boolean(art)&&s.mode!=='listen';const background=showArt?`url('picture-assets/${art.file}')`:'none';const title=s.mode==='picture'?(art.question||'Which answer matches the illustration?'):s.mode==='listen'?(art?.listenQuestion||'Listen. Which item did you hear?'):item.symbol?'Choose the correct reading or name.':'Choose the correct meaning.';
dialog.innerHTML=`<header class="lm-fc-header"><div><span>EXPEDITION HUB</span><h2 id="lmFlashcardHeading" tabindex="-1">${esc(s.title)}</h2></div><button type="button" data-fc-close aria-label="Return to lesson">✕</button></header><div class="lm-fc-content"><div class="lm-fc-mode" role="group" aria-label="Question mode"><button data-fc-mode="word" aria-pressed="${s.mode==='word'}">Word / character</button><button data-fc-mode="picture" aria-pressed="${s.mode==='picture'}" ${art?'':'disabled'} title="${art?'Identify the illustration':'No matching illustration yet'}">Picture</button><button data-fc-mode="listen" aria-pressed="${s.mode==='listen'}" ${hasVoice?'':'disabled'} title="${hasVoice?'Listen without a written clue':'Pronunciation is unavailable for this item'}">Listening</button></div><div class="lm-fc-scene ${s.mode==='picture'?'is-picture':''}" style="--fc-art:${background}"><div class="lm-fc-scene-copy">${showArt?`<span class="lm-fc-art-description" role="img" aria-label="${esc(art.alt)}"></span>`:''}<span class="lm-fc-kicker">${s.mode==='picture'?'PICTURE CLUE':s.mode==='listen'?'SOUND CLUE':'WRITTEN CLUE'}</span>${s.mode==='word'?`<div class="lm-fc-term" lang="${esc(s.language)}">${esc(item.term)}</div>`:s.mode==='listen'?'<div class="lm-fc-sound" aria-hidden="true">♫</div>':''}<h3>${esc(title)}</h3>${(s.mode==='picture'||(s.mode==='word'&&art?.contextText))&&art?.clueText?`<p class="lm-fc-example ${art.contextText?'lm-fc-context':''}" lang="${esc(art.clueLanguage||(art.contextText?'en':s.language))}">${esc(art.clueText)}</p>`:''}${s.mode==='word'&&item.symbol&&art?.clueSpeech?`<p class="lm-fc-pictured-word"><small>PICTURED EXAMPLE</small><span lang="${esc(s.language)}">${esc(art.exampleText||art.clueSpeech)}</span></p>`:''}${showArt&&art.clueSpeech&&(s.mode==='picture'||art.clueSpeech!==item.speech)?`<button data-fc-example ${hasAudio(art.clueSpeech)?'':'disabled'}>▶ Hear the pictured word</button>`:''}${s.mode!=='picture'?`<button data-fc-speak ${hasVoice?'':'disabled'}>▶ ${s.mode==='listen'?'Play sound':'Hear pronunciation'}</button>`:''}</div><span class="lm-fc-scene-note">${showArt?esc(art.note||(item.symbol?'Picture hints at the first sound':'Picture shows the word’s meaning')):''}</span></div><div class="lm-fc-answers" role="group" aria-label="Answer choices">${s.options.map((value,index)=>`<button type="button" data-fc-answer="${index}"><span>${esc(value)}</span></button>`).join('')}</div><div class="lm-fc-feedback" data-fc-status role="status">${s.options.length<4?'This set has fewer than four distinct answers.':s.preview?'Preview practice · no progress saved.':'Choose one answer. This practice updates item mastery, not mine XP.'}</div><footer class="lm-fc-footer"><span>${s.index+1} / ${s.items.length}</span><button type="button" data-fc-next disabled>${s.index===s.items.length-1?'Return to lesson':'Next card →'}</button></footer></div>`;
dialog.querySelector('[data-fc-close]').onclick=()=>dialog.close();dialog.querySelector('[data-fc-example]')?.addEventListener('click',()=>speak(art.clueSpeech));dialog.querySelector('[data-fc-speak]')?.addEventListener('click',speak);dialog.querySelectorAll('[data-fc-mode]').forEach(b=>b.onclick=()=>{cancelAudio();s.mode=b.dataset.fcMode;render()});dialog.querySelectorAll('[data-fc-answer]').forEach(b=>b.onclick=()=>grade(Number(b.dataset.fcAnswer)));dialog.querySelector('[data-fc-next]').onclick=()=>{if(s.index===s.items.length-1){dialog.close();return}s.index++;render()};dialog.scrollTop=0;if(dialog.open)dialog.querySelector('#lmFlashcardHeading').focus({preventScroll:true});}
function grade(index){const s=session;if(!s||s.answered)return;s.answered=true;const correct=s.options[index]===s.answer,item=s.items[s.index];dialog.querySelectorAll('[data-fc-answer]').forEach((b,i)=>{b.disabled=true;if(s.options[i]===s.answer)b.classList.add('correct');else if(i===index)b.classList.add('wrong')});dialog.querySelectorAll('[data-fc-mode]').forEach(b=>b.disabled=true);const status=dialog.querySelector('[data-fc-status]');status.className=`lm-fc-feedback ${correct?'correct':'wrong'}`;status.textContent=`${correct?'✓ Correct.':'Not quite.'} ${item.term} — ${item.meaning}`;const art=window.LanguageMinerPictures?.imageFor(item,{language:s.language});if(art?.explanation)status.textContent+=' '+art.explanation;if(!s.graded.has(s.index)){s.graded.add(s.index);try{s.onGrade?.(item,correct)}catch(error){console.error('Flashcard mastery could not be saved',error);status.textContent+=' Your mastery could not be saved.'}}dialog.querySelector('[data-fc-next]').disabled=false;}
function open({items,index=0,language='ja',known='en',title='Lesson practice',onGrade=null,preview=false}={}){if(!Array.isArray(items)||!items.length)return false;const requested=items[Math.min(items.length-1,Math.max(0,Number(index)||0))],available=items.filter(i=>window.LanguageMinerVocabulary?.available(i)!==false);if(!available.length||!available.includes(requested))return false;index=available.indexOf(requested);const clean=available.map(i=>normalize(i,language,known));if(clean.some(i=>!i.term||!i.meaning))return false;focusBefore=document.activeElement;session={items:clean,index:Math.min(clean.length-1,Math.max(0,Number(index)||0)),language,known,title,onGrade,preview,mode:'word',graded:new Set()};render();if(!dialog.open)dialog.showModal();return true;}
function chips(items,{kind,stage=0,lesson=0,section='vocabulary',language='ja'}={}){return `<div class="lm-item-flashcards" aria-label="Click an item to practice">${items.map((item,index)=>{const term=item.symbol||item.forms?.[language]||item.jp||item[0],name=item.name||item.reading||item[1]||'';return `<button type="button" data-lm-flashcard="${kind}" data-fc-stage="${stage}" data-fc-lesson="${lesson}" data-fc-section="${section}" data-fc-index="${index}"><strong lang="${esc(language)}">${esc(term)}</strong>${name?`<small>${esc(name)}</small>`:''}</button>`}).join('')}</div>`}
window.LanguageMinerFlashcards=Object.freeze({open,chips});
dialog.addEventListener('close',()=>{cancelAudio();session=null;if(focusBefore?.isConnected)focusBefore.focus()});dialog.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||!session||session.answered)return;const i='abcd'.indexOf(e.key.toLowerCase());if(i>=0&&i<session.options.length){e.preventDefault();grade(i)}});
window.speechSynthesis?.addEventListener('voiceschanged',()=>{if(!session||session.answered)return;const item=session.items[session.index],art=window.LanguageMinerPictures?.imageFor(item,{language:session.language}),ready=hasAudio(item.speech);const b=dialog.querySelector('[data-fc-mode="listen"]');if(b)b.disabled=!ready;dialog.querySelectorAll('[data-fc-speak]').forEach(play=>play.disabled=!ready);dialog.querySelectorAll('[data-fc-example]').forEach(play=>play.disabled=!hasAudio(art?.clueSpeech))});
function boot(){document.body.appendChild(dialog);document.addEventListener('click',e=>{const b=e.target.closest('[data-lm-flashcard]');if(!b)return;e.preventDefault();e.stopPropagation();const d=b.dataset;if(d.lmFlashcard==='course')window.LanguageMinerCourseFlashcards?.open(Number(d.fcStage),d.fcSection,Number(d.fcLesson),Number(d.fcIndex));else window.openJapaneseItemFlashcard?.(d.lmFlashcard,Number(d.fcStage),Number(d.fcLesson),Number(d.fcIndex));});const query=new URLSearchParams(location.search);if(query.has('flashcard')){const vocabulary=window.LANGUAGE_MINER_MULTILINGUAL_COURSE_DATA?.vocabulary||[];const language=query.get('language')||'ja';const kana=language==='ja'&&typeof kanaSetForStage==='function'?kanaSetForStage(query.get('script')==='katakana'?1:0).map(([symbol,name])=>({symbol,name})):(window.LanguageMinerCourseWriting?.alphabetSystem(language)?.units||[]);const alphabet=query.get('flashcard')==='alphabet';const requestedId=Number(query.get('id')),offset=requestedId>0?Math.floor((requestedId-1)/25)*25:0;const stage=Number(query.get('stage')),advanced=!alphabet&&language==='ja'&&stage>=2&&stage<=6&&typeof jlptVocabularyWords==='function';const nativeOffset=advanced?Math.floor((requestedId>0?requestedId-1:Number(query.get('item')??1))/25)*25:0;const items=alphabet?kana:advanced?jlptVocabularyWords(stage).slice(nativeOffset,nativeOffset+25):vocabulary.slice(offset,offset+25).filter(i=>window.LanguageMinerVocabulary?.available(i)!==false);const selected=alphabet&&query.has('symbol')?items.findIndex(i=>i.symbol===query.get('symbol')):requestedId>0?items.findIndex(i=>advanced?i.sourceIndex===requestedId-1:i.id===requestedId):Number(query.get('item')??(alphabet?0:1))-(advanced?nativeOffset:0);open({items,index:Math.max(0,selected),language,title:alphabet?(language==='ja'?(query.get('script')==='katakana'?'Katakana':'Hiragana')+' · character practice':'Alphabet · character practice'):advanced?'Japanese vocabulary · N'+(7-stage):'Vocabulary · Lesson '+(Math.floor(offset/25)+1),preview:true});if(query.get('mode')==='picture')dialog.querySelector('[data-fc-mode="picture"]:not(:disabled)')?.click();}}
if(document.readyState==='complete')boot();else document.addEventListener('DOMContentLoaded',boot,{once:true});
})();
