const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});const ctx=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});let serverDay='2026-09-24',row=null,commits=0;const errors=[];
await ctx.route('**/*.supabase.co/**',async route=>{const url=route.request().url();let value=[];if(url.includes('/rpc/save_player_state')){const p=route.request().postDataJSON();if(row&&row.revision!==p.p_base_revision)value=[{...row,accepted:false}];else{if(p.p_game_state.dailyGolem?.claims>(row?.game_state?.dailyGolem?.claims||0))commits++;row={user_id:'golem-qa',game_state:p.p_game_state,course_settings:p.p_course_settings,revision:(row?.revision||0)+1,updated_at:serverDay+'T12:00:00.000Z'};value=[{...row,accepted:true}];}}else if(url.includes('/rpc/load_player_save'))value=row?[row]:[];else if(url.includes('/auth/v1/user'))value={id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});});
await ctx.addInitScript(()=>{if(!localStorage.getItem('jm_profiles')){localStorage.setItem('jm_profiles',JSON.stringify([{id:'cloud-golem-qa',name:'Golem QA',cloudUserId:'golem-qa'}]));localStorage.setItem('jm_active_profile','cloud-golem-qa');localStorage.setItem('lm_multilingual_functional_preview_v1:cloud:golem-qa',JSON.stringify({known:'en',learning:'ja',placements:{ja:{status:'tested'}}}));localStorage.setItem('jm_profile_cloud-golem-qa',JSON.stringify({onboardingComplete:true,placementTestCompleted:true,voiceEnabled:false,autoSpeak:false,hearts:14,maxHearts:14}));}localStorage.setItem('lm_cloud_session_v2',JSON.stringify({accessToken:'qa-test',refreshToken:'qa-refresh',expiresAt:9999999999,user:{id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}}}));});
const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.GOLEM_TEST_URL||'http://127.0.0.1:8765/')+'index.html');await page.waitForFunction(()=>window.LanguageMinerDailyGolem&&typeof state!=='undefined'&&state.dailyGolem?.day);if(await page.locator('#lmMultilingualOverlay.open').count())await page.locator('#lmFlowClose').click();await page.screenshot({path:'work/golem-initial.png',fullPage:true});console.log('loaded',await page.locator('#dailyGolem').innerText());


const before=await page.evaluate(()=>JSON.stringify(state.dailyGolem));
await page.evaluate(()=>{window.frames3d=[];window.motionTimer=setInterval(()=>{const s=document.querySelector('.dg-scene');if(s?._dg3dInfo)frames3d.push({phase:s.dataset.phase,...s._dg3dInfo,pose:{...s._dg3dPose},core:{...s._dgCorePos}});},20);});
await page.getByRole('button',{name:'Preview animation',exact:true}).click();
await page.waitForSelector('.dg-scene[data-renderer="3d"].dg-prepared');
assert(await page.locator('.dg-3d-canvas').isVisible(),'Live 3D canvas is visible');
await page.waitForFunction(()=>document.querySelector('.dg-scene')?.dataset.phase==='windup');await page.waitForTimeout(650);await page.locator('.dg-dialog').screenshot({path:'work/golem-3d-windup.png'});
await page.waitForFunction(()=>document.querySelector('.dg-scene')?.dataset.phase==='impact');await page.locator('.dg-dialog').screenshot({path:'work/golem-3d-impact.png'});
await page.waitForFunction(()=>document.querySelector('.dg-scene')?.dataset.phase==='victory');await page.waitForTimeout(1000);await page.locator('.dg-dialog').screenshot({path:'work/golem-3d-victory.png'});
await page.getByRole('button',{name:'Continue',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('.dg-3d-still')?.naturalWidth>0);await page.locator('.dg-dialog').screenshot({path:'work/golem-3d-finished.png'});await page.getByRole('button',{name:'Continue',exact:true}).click();
assert.equal(await page.evaluate(()=>JSON.stringify(state.dailyGolem)),before);assert.equal(commits,0);
const frames=await page.evaluate(()=>{clearInterval(motionTimer);return frames3d});const closed=frames.filter(f=>f.pose.open<.01&&f.pose.tool>.99);console.log('motion metrics',{samples:frames.length,maxGrip:Math.max(...closed.map(f=>f.gripError)),maxSupport:Math.max(...closed.map(f=>f.supportError)),maxFoot:Math.max(...frames.flatMap(f=>f.feet.map((v,i)=>Math.hypot(v[0]-[-.41,-.89][i],v[1]-.085,v[2]-[.13,-.13][i]))))});
assert(frames.length>40);assert(frames.every(f=>f.boneCount>=60&&f.triangles>10000),'A weighted 3D character is rendered');assert(closed.every(f=>f.gripError<.01&&f.supportError<.01),'Both rendered palm anchors follow the shaft');assert(frames.every(f=>f.feet.every((v,i)=>Math.hypot(v[0]-[-.41,-.89][i],v[1]-.085,v[2]-[.13,-.13][i])<.01)),'Both feet stay planted');assert(Math.max(...frames.map(f=>f.hip[0]))-Math.min(...frames.map(f=>f.hip[0]))>.20,'Whole-body weight shift');assert(Math.max(...frames.map(f=>f.hip[1]))-Math.min(...frames.map(f=>f.hip[1]))>.10,'Knees absorb the strike');const held=frames.filter(f=>f.phase==='victory');assert(held.every(f=>Math.hypot(f.core.x-f.hand.x,f.core.y-(f.hand.y-26))<.1),'Core stays in the moving hand');console.log('Two-handed 3D skeleton, planted stance, Core catch and safe preview passed');
await page.evaluate(()=>{state.dailyGolem.claims=6;state.dailyGolem.questions=5;LanguageMinerDailyGolem.refresh();window.setJapaneseMinerVerifiedSupporterEntitlement({tier:1,connected:true,source:'qa'});state.equippedPickaxeSkin='amethyst';});
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Preview animation',exact:true}).click();await page.waitForSelector('.dg-scene[data-renderer="3d"].dg-prepared');assert(await page.locator('.dg-scene.prismatic').count());const finish=await page.evaluate(()=>document.querySelector('.dg-scene')._dg3dInfo);assert.equal(finish.pickaxeId,'amethyst');assert.equal(finish.pickaxeColor,'ba7cf4');await page.waitForFunction(()=>document.querySelector('.dg-scene')?.dataset.phase==='impact');await page.locator('.dg-dialog').screenshot({path:'work/golem-3d-mobile.png'});await page.getByRole('button',{name:'Skip animation',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();
await page.setViewportSize({width:844,height:390});await page.getByRole('button',{name:'Preview animation',exact:true}).click();await page.waitForSelector('.dg-scene.dg-prepared');const layout=await page.evaluate(()=>{const d=document.querySelector('.dg-dialog'),b=d.querySelector('.dg-skip').getBoundingClientRect();return{overflow:d.scrollWidth>d.clientWidth,buttonVisible:b.top>=0&&b.bottom<=innerHeight}});assert(!layout.overflow&&layout.buttonVisible,'Landscape controls fit');await page.locator('.dg-dialog').screenshot({path:'work/golem-3d-landscape.png'});await page.getByRole('button',{name:'Skip animation',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();
const wardrobe=await page.evaluate(async()=>{const module=await import('./golem-3d-v1/scene.js'),c=document.createElement('canvas');document.body.append(c);const rig=await module.create(c,{skin:'deep',hairColor:'pink',hairStyle:'bun',shirt:'academy',pants:'khaki',gloves:'crystal',accessories:['glasses','helmet','scarf']},'emerald');try{return rig.pose(rig.keys.loading);}finally{rig.dispose();c.remove();}});assert.equal(wardrobe.skinColor,'795033');assert.equal(wardrobe.shirtColor,'417bc3');assert.equal(wardrobe.pickaxeColor,'36cf91');assert.equal(wardrobe.hairStyle,'Buns');console.log('Selected skin, shirt, hair, accessories and pickaxe rendering passed');
await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Preview animation',exact:true}).click();await page.waitForSelector('.dg-scene[data-reduced="true"]');await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(errors.length,0,errors.join(';'));console.log('3D mobile, prismatic, equipped pickaxe, landscape and reduced motion passed');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
