const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});const ctx=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});let serverDay='2026-09-24',row=null,commits=0;const errors=[];
await ctx.route('**/*.supabase.co/**',async route=>{const url=route.request().url();let value=[];if(url.includes('/rpc/save_player_state')){const p=route.request().postDataJSON();if(row&&row.revision!==p.p_base_revision)value=[{...row,accepted:false}];else{if(p.p_game_state.dailyGolem?.claims>(row?.game_state?.dailyGolem?.claims||0))commits++;row={user_id:'golem-qa',game_state:p.p_game_state,course_settings:p.p_course_settings,revision:(row?.revision||0)+1,updated_at:serverDay+'T12:00:00.000Z'};value=[{...row,accepted:true}];}}else if(url.includes('/rpc/load_player_save'))value=row?[row]:[];else if(url.includes('/auth/v1/user'))value={id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});});
await ctx.addInitScript(()=>{if(!localStorage.getItem('jm_profiles')){localStorage.setItem('jm_profiles',JSON.stringify([{id:'cloud-golem-qa',name:'Golem QA',cloudUserId:'golem-qa'}]));localStorage.setItem('jm_active_profile','cloud-golem-qa');localStorage.setItem('lm_multilingual_functional_preview_v1:cloud:golem-qa',JSON.stringify({known:'en',learning:'ja',placements:{ja:{status:'tested'}}}));localStorage.setItem('jm_profile_cloud-golem-qa',JSON.stringify({onboardingComplete:true,placementTestCompleted:true,voiceEnabled:false,autoSpeak:false,hearts:14,maxHearts:14}));}localStorage.setItem('lm_cloud_session_v2',JSON.stringify({accessToken:'qa-test',refreshToken:'qa-refresh',expiresAt:9999999999,user:{id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}}}));});
const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/index.html');await page.waitForFunction(()=>window.LanguageMinerDailyGolem&&typeof state!=='undefined'&&state.dailyGolem?.day);if(await page.locator('#lmMultilingualOverlay.open').count())await page.locator('#lmFlowClose').click();await page.screenshot({path:'work/golem-initial.png',fullPage:true});console.log('loaded',await page.locator('#dailyGolem').innerText());
await page.evaluate(()=>{const q={id:'test'};LanguageMinerDailyGolem.practice(q);LanguageMinerDailyGolem.practice(q);});assert.equal(await page.evaluate(()=>state.dailyGolem.questions),1);
assert.equal(await page.locator('#dailyGolem details, #dailyGolem summary').count(),0,'Removed 7-day rewards dropdown');
for(let i=0;i<4;i++)await page.evaluate(i=>LanguageMinerEconomy.recordCourseAnswer({correct:true,learningLanguage:['es','fr','ja','ko'][i],item:{id:'test'+i,forms:{}},stage:0,section:'vocabulary'}),i);
assert.equal(await page.evaluate(()=>state.dailyGolem.questions),5);await page.getByRole('button',{name:'Break Golem',exact:true}).waitFor();await page.evaluate(()=>render());const before=await page.evaluate(()=>({n:totalStoneValue(),h:state.hints,s:state.shields}));await page.getByRole('button',{name:'Break Golem',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.dg-scene')?.dataset.phase==='victory');await page.screenshot({path:'work/golem-victory.png'});await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await page.evaluate(()=>totalStoneValue()),before.n+500);assert.equal(commits,1);await page.reload();await page.waitForFunction(()=>state.dailyGolem?.lastClaim==='2026-09-24');assert.equal(await page.evaluate(()=>state.dailyGolem.claims),1);await page.evaluate(()=>LanguageMinerI18n.setLocale('es',{learning:'fr'}));assert.equal(await page.evaluate(()=>state.dailyGolem.claims),1);console.log('claim/reload/language passed');
serverDay='2026-09-28';await page.evaluate(()=>LanguageMinerDailyGolem.sync());await page.waitForFunction(()=>state.dailyGolem?.day==='2026-09-28');assert.equal(await page.evaluate(()=>state.dailyGolem.claims),1);assert.equal(await page.evaluate(()=>state.dailyGolem.streak),0);assert.equal(await page.evaluate(()=>state.dailyGolem.questions),0);
await page.evaluate(()=>LanguageMinerI18n.setLocale('en'));assert.match(await page.locator('#dailyGolem small').innerText(),/Day 1\/7/);assert.equal(await page.locator('#dailyGolem details, #dailyGolem summary').count(),0);await page.evaluate(()=>languageMinerPushCloudSave());await page.reload();await page.waitForFunction(()=>state.dailyGolem?.day==='2026-09-28');assert.equal(await page.evaluate(()=>state.dailyGolem.streak),0,'Reset persists after reload');assert.equal(await page.evaluate(()=>state.dailyGolem.claims),1,'Lifetime claims survive reset');
await page.evaluate(()=>{for(let i=0;i<5;i++)LanguageMinerDailyGolem.practice({id:'restart-'+i});});const restartNuggets=await page.evaluate(()=>totalStoneValue());await page.getByRole('button',{name:'Break Golem',exact:true}).click();assert.match(await page.locator('.dg-dialog header small').innerText(),/Day 1\/7/);await page.getByRole('button',{name:'Skip animation',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await page.evaluate(()=>totalStoneValue()),restartNuggets+500);assert.equal(await page.evaluate(()=>state.dailyGolem.claims),2);assert.equal(await page.evaluate(()=>state.dailyGolem.streak),1);assert.equal(await page.evaluate(()=>state.dailyGolem.receipt.track),1);console.log('missed day resets to Day 1, persists and grants Day 1 reward');
serverDay='2026-09-29';await page.evaluate(()=>LanguageMinerDailyGolem.sync());await page.waitForFunction(()=>state.dailyGolem?.day==='2026-09-29');await page.evaluate(()=>{state.dailyGolem.claims=7;state.dailyGolem.streak=6;for(let i=0;i<5;i++)LanguageMinerDailyGolem.practice({id:'d7-'+i});});assert.match(await page.locator('#dailyGolem small').innerText(),/Day 7\/7/);await page.getByRole('button',{name:'Break Golem',exact:true}).click();assert.match(await page.locator('.dg-dialog header small').innerText(),/Day 7\/7/);await page.getByRole('button',{name:'Skip animation',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await page.evaluate(()=>state.dailyGolem.weeks),1);assert.equal(await page.evaluate(()=>state.dailyGolem.claims),8);assert.equal(await page.evaluate(()=>state.dailyGolem.streak),7);assert.equal(await page.evaluate(()=>state.dailyGolem.receipt.track),7);assert.match(await page.locator('#dailyGolem small').innerText(),/Day 7\/7/);console.log('Day 7 follows streak despite different lifetime claims');
await page.setViewportSize({width:390,height:844});await page.locator('#dailyGolem').scrollIntoViewIfNeeded();await page.screenshot({path:'work/golem-mobile.png',fullPage:true});const bounds=await page.locator('#dailyGolem').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=391);console.log('mobile passed',bounds,'errors',errors);fs.writeFileSync('work/golem-qa-result.json',JSON.stringify({commits,errors,bounds},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});



