const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});const ctx=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});let serverDay='2026-09-24',row=null,commits=0;const errors=[];
await ctx.route('**/*.supabase.co/**',async route=>{const url=route.request().url();let value=[];if(url.includes('/rpc/save_player_state')){const p=route.request().postDataJSON();if(row&&row.revision!==p.p_base_revision)value=[{...row,accepted:false}];else{if(p.p_game_state.dailyGolem?.claims>(row?.game_state?.dailyGolem?.claims||0))commits++;row={user_id:'golem-qa',game_state:p.p_game_state,course_settings:p.p_course_settings,revision:(row?.revision||0)+1,updated_at:serverDay+'T12:00:00.000Z'};value=[{...row,accepted:true}];}}else if(url.includes('/rpc/load_player_save'))value=row?[row]:[];else if(url.includes('/auth/v1/user'))value={id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});});
await ctx.addInitScript(()=>{if(!localStorage.getItem('jm_profiles')){localStorage.setItem('jm_profiles',JSON.stringify([{id:'cloud-golem-qa',name:'Golem QA',cloudUserId:'golem-qa'}]));localStorage.setItem('jm_active_profile','cloud-golem-qa');localStorage.setItem('lm_multilingual_functional_preview_v1:cloud:golem-qa',JSON.stringify({known:'en',learning:'ja',placements:{ja:{status:'tested'}}}));localStorage.setItem('jm_profile_cloud-golem-qa',JSON.stringify({onboardingComplete:true,placementTestCompleted:true,voiceEnabled:false,autoSpeak:false,hearts:14,maxHearts:14}));}localStorage.setItem('lm_cloud_session_v2',JSON.stringify({accessToken:'qa-test',refreshToken:'qa-refresh',expiresAt:9999999999,user:{id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}}}));});
const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/index.html');await page.waitForFunction(()=>window.LanguageMinerDailyGolem&&typeof state!=='undefined'&&state.dailyGolem?.day);if(await page.locator('#lmMultilingualOverlay.open').count())await page.locator('#lmFlowClose').click();await page.screenshot({path:'work/golem-initial.png',fullPage:true});console.log('loaded',await page.locator('#dailyGolem').innerText());

await page.evaluate(()=>{for(let i=0;i<5;i++)LanguageMinerDailyGolem.practice({id:'q'+i});});await page.evaluate(()=>languageMinerPushCloudSave());
// Persist the claim but drop the response; recovery must find its receipt.
await ctx.route('**/rpc/save_player_state',async route=>{const p=route.request().postDataJSON();if(p.p_game_state.dailyGolem?.claims>(row.game_state.dailyGolem?.claims||0)){row={...row,game_state:p.p_game_state,course_settings:p.p_course_settings,revision:row.revision+1,updated_at:serverDay+'T12:00:00.000Z'};commits++;await route.abort('failed');}else await route.fallback();});
assert.equal(await page.evaluate(()=>languageMinerCommitDailyGolem('2026-09-24').then(x=>x.nuggets)),500);assert.equal(commits,1);assert.equal(await page.evaluate(()=>languageMinerCommitDailyGolem('2026-09-24').then(()=>true,()=>false)),false);assert.equal(commits,1);console.log('lost response recovered, retry cannot duplicate');
await ctx.unroute('**/rpc/save_player_state');serverDay='2026-09-25';await page.evaluate(()=>LanguageMinerDailyGolem.sync());await page.waitForFunction(()=>state.dailyGolem.day==='2026-09-25');await page.evaluate(()=>{for(let i=0;i<5;i++)LanguageMinerDailyGolem.practice({id:'d2'+i});});await page.evaluate(()=>languageMinerPushCloudSave());const hints=await page.evaluate(()=>state.hints);await ctx.route('**/rpc/save_player_state',route=>route.abort('failed'));assert.equal(await page.evaluate(()=>languageMinerCommitDailyGolem('2026-09-25').then(()=>true,()=>false)),false);assert.equal(await page.evaluate(()=>state.hints),hints);assert.equal(row.game_state.dailyGolem.claims,1);console.log('offline claim adds no inventory');await ctx.unroute('**/rpc/save_player_state');
await page.evaluate(()=>{state.dailyGolem.claims=27;state.dailyGolem.streak=27;state.dailyGolem.weeks=3;save();});await page.evaluate(()=>languageMinerCommitDailyGolem('2026-09-25'));assert.equal(await page.evaluate(()=>state.dailyGolem.weeks),4);await page.evaluate(()=>LanguageMinerDailyGolem.refresh());await page.getByRole('button',{name:'Equip Daily Miner',exact:true}).click();assert.equal(await page.locator('.dg-equipped-title').innerText(),'✦ Daily Miner');
serverDay='2026-09-26';await page.evaluate(()=>LanguageMinerDailyGolem.sync());await page.waitForFunction(()=>state.dailyGolem.day==='2026-09-26');assert.equal(await page.evaluate(()=>state.dailyGolem.streak%7),0);assert.match(await page.locator('#dailyGolem small').innerText(),/Day 1\/7/);serverDay='2026-09-27';await page.evaluate(()=>LanguageMinerDailyGolem.sync());await page.waitForFunction(()=>state.dailyGolem.day==='2026-09-27');assert.equal(await page.evaluate(()=>state.dailyGolem.streak),0);assert.equal(await page.evaluate(()=>state.dailyGolem.claims),28);assert.equal(await page.evaluate(()=>state.dailyGolem.weeks),4);assert.equal(await page.locator('.dg-equipped-title').innerText(),'✦ Daily Miner');await page.setViewportSize({width:320,height:740});await page.locator('#dailyGolem').scrollIntoViewIfNeeded();const b=await page.locator('#dailyGolem').boundingBox();assert(b.x>=0&&b.x+b.width<=320);console.log('title survives missed day, Day7 wrap and 320px layout passed');assert.equal(errors.length,0);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
