const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});const ctx=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});let serverDay='2026-09-24',row=null,commits=0;const errors=[];
await ctx.route('**/*.supabase.co/**',async route=>{const url=route.request().url();let value=[];if(url.includes('/rpc/save_player_state')){const p=route.request().postDataJSON();if(row&&row.revision!==p.p_base_revision)value=[{...row,accepted:false}];else{if(p.p_game_state.dailyGolem?.claims>(row?.game_state?.dailyGolem?.claims||0))commits++;row={user_id:'golem-qa',game_state:p.p_game_state,course_settings:p.p_course_settings,revision:(row?.revision||0)+1,updated_at:serverDay+'T12:00:00.000Z'};value=[{...row,accepted:true}];}}else if(url.includes('/rpc/load_player_save'))value=row?[row]:[];else if(url.includes('/auth/v1/user'))value={id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});});
await ctx.addInitScript(()=>{if(!localStorage.getItem('jm_profiles')){localStorage.setItem('jm_profiles',JSON.stringify([{id:'cloud-golem-qa',name:'Golem QA',cloudUserId:'golem-qa'}]));localStorage.setItem('jm_active_profile','cloud-golem-qa');localStorage.setItem('lm_multilingual_functional_preview_v1:cloud:golem-qa',JSON.stringify({known:'en',learning:'ja',placements:{ja:{status:'tested'}}}));localStorage.setItem('jm_profile_cloud-golem-qa',JSON.stringify({onboardingComplete:true,placementTestCompleted:true,voiceEnabled:false,autoSpeak:false,hearts:14,maxHearts:14}));}localStorage.setItem('lm_cloud_session_v2',JSON.stringify({accessToken:'qa-test',refreshToken:'qa-refresh',expiresAt:9999999999,user:{id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}}}));});
const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/index.html');await page.waitForFunction(()=>window.LanguageMinerDailyGolem&&typeof state!=='undefined'&&state.dailyGolem?.day);if(await page.locator('#lmMultilingualOverlay.open').count())await page.locator('#lmFlowClose').click();await page.screenshot({path:'work/golem-initial.png',fullPage:true});console.log('loaded',await page.locator('#dailyGolem').innerText());

await page.locator('#dailyGolem').screenshot({path:'work/golem-v2-panel.png'});const before=await page.evaluate(()=>JSON.stringify(state.dailyGolem));await page.getByRole('button',{name:'Preview animation',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.dg-scene')?.dataset.phase==='windup');await page.waitForTimeout(650);await page.locator('.dg-dialog').screenshot({path:'work/golem-v2-windup.png'});
await page.waitForFunction(()=>document.querySelector('.dg-scene')?.dataset.phase==='impact');const contact=await page.evaluate(()=>{const tool=document.querySelector('.dg-tool'),impact=document.querySelector('.dg-impact-anchor'),tip=new DOMPoint(208,433).matrixTransform(tool.getScreenCTM()),hit=new DOMPoint(0,0).matrixTransform(impact.getScreenCTM());return {tip:{x:tip.x,y:tip.y},hit:{x:hit.x,y:hit.y},distance:Math.hypot(tip.x-hit.x,tip.y-hit.y),transform:getComputedStyle(document.querySelector('.dg-swing-arm')).transform};});await page.locator('.dg-dialog').screenshot({path:'work/golem-v2-impact.png'});assert(contact.distance<10,JSON.stringify(contact));console.log('Pickaxe physically connects',contact);
await page.waitForFunction(()=>document.querySelector('.dg-scene')?.dataset.phase==='victory');await page.waitForTimeout(800);await page.locator('.dg-dialog').screenshot({path:'work/golem-v2-victory.png'});await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.stringify(state.dailyGolem)),before);assert.equal(commits,0);console.log('Preview never grants or consumes rewards');
await page.evaluate(()=>{state.dailyGolem.claims=6;state.dailyGolem.questions=5;LanguageMinerDailyGolem.refresh();});await page.evaluate(()=>languageMinerPushCloudSave());commits=0;await page.setViewportSize({width:390,height:844});await page.locator('#dailyGolem').screenshot({path:'work/golem-v2-prismatic-mobile.png'});await page.getByRole('button',{name:'Preview animation',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.dg-scene')?.dataset.phase==='impact');await page.locator('.dg-dialog').screenshot({path:'work/golem-v2-impact-mobile.png'});await page.getByRole('button',{name:'Skip animation',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();
await page.evaluate(()=>{window.setJapaneseMinerVerifiedSupporterEntitlement({tier:1,connected:true,source:'qa'});state.equippedPickaxeSkin='amethyst';});await page.getByRole('button',{name:'Preview animation',exact:true}).click();await page.waitForSelector('.dg-tool[data-equipped-pickaxe=amethyst]');await page.getByRole('button',{name:'Skip animation',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();console.log('Equipped amethyst pickaxe used');
await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Preview animation',exact:true}).click();await page.waitForSelector('.dg-scene[data-reduced="true"]');await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(commits,0);assert.equal(errors.length,0);console.log('Mobile/prismatic and reduced-motion preview passed');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
