const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});const ctx=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});let serverDay='2026-09-24',row=null,commits=0;const errors=[];
await ctx.route('**/*.supabase.co/**',async route=>{const url=route.request().url();let value=[];if(url.includes('/rpc/save_player_state')){const p=route.request().postDataJSON();if(row&&row.revision!==p.p_base_revision)value=[{...row,accepted:false}];else{if(p.p_game_state.dailyGolem?.claims>(row?.game_state?.dailyGolem?.claims||0))commits++;row={user_id:'golem-qa',game_state:p.p_game_state,course_settings:p.p_course_settings,revision:(row?.revision||0)+1,updated_at:serverDay+'T12:00:00.000Z'};value=[{...row,accepted:true}];}}else if(url.includes('/rpc/load_player_save'))value=row?[row]:[];else if(url.includes('/auth/v1/user'))value={id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});});
await ctx.addInitScript(()=>{if(!localStorage.getItem('jm_profiles')){localStorage.setItem('jm_profiles',JSON.stringify([{id:'cloud-golem-qa',name:'Golem QA',cloudUserId:'golem-qa'}]));localStorage.setItem('jm_active_profile','cloud-golem-qa');localStorage.setItem('lm_multilingual_functional_preview_v1:cloud:golem-qa',JSON.stringify({known:'en',learning:'ja',placements:{ja:{status:'tested'}}}));localStorage.setItem('jm_profile_cloud-golem-qa',JSON.stringify({onboardingComplete:true,placementTestCompleted:true,voiceEnabled:false,autoSpeak:false,hearts:14,maxHearts:14}));}localStorage.setItem('lm_cloud_session_v2',JSON.stringify({accessToken:'qa-test',refreshToken:'qa-refresh',expiresAt:9999999999,user:{id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}}}));});
const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/index.html');await page.waitForFunction(()=>window.LanguageMinerDailyGolem&&typeof state!=='undefined'&&state.dailyGolem?.day);if(await page.locator('#lmMultilingualOverlay.open').count())await page.locator('#lmFlowClose').click();await page.screenshot({path:'work/golem-initial.png',fullPage:true});console.log('loaded',await page.locator('#dailyGolem').innerText());

// Exercise actual Japanese answers and the next-question UI.
await page.evaluate(()=>{state.smartReview=false;state.soundEnabled=false;state.voiceEnabled=false;mine();});
for(let i=0;i<2;i++){const correct=await page.evaluate(()=>state.active.a);const buttons=page.locator('#answers button');const count=await buttons.count();let chosen=false;for(let j=0;j<count;j++){if((await buttons.nth(j).innerText()).trim()===String(correct).trim()){await buttons.nth(j).click();chosen=true;break;}}assert(chosen,'correct answer button');await page.waitForFunction(()=>state.answered);assert.equal(await page.evaluate(()=>state.dailyGolem.questions),i+1);if(i===0)await page.locator('#quickMineBtn').click();}
console.log('Japanese UI answers increment once');
await page.evaluate(()=>{const settings=LanguageMinerCourseCloud.exportCurrent();settings.learning='es';settings.placements.es={status:'tested'};LanguageMinerCourseCloud.importCurrent(settings);LanguageMinerCourseNavigation.next();});
const foreign=page.locator('[data-lm-course-answer]');await foreign.first().click();assert.equal(await page.evaluate(()=>state.dailyGolem.questions),3);console.log('Spanish UI answer shares same track');
// Reload a counted in-progress question: its marker survives serialization.
await page.evaluate(()=>{const q={id:'persisted'};LanguageMinerDailyGolem.practice(q);state.active=q;save();});await page.evaluate(()=>languageMinerPushCloudSave());await page.reload();await page.waitForFunction(()=>state.dailyGolem?.questions===4);await page.evaluate(()=>LanguageMinerDailyGolem.practice(state.active));assert.equal(await page.evaluate(()=>state.dailyGolem.questions),4);
// Moving the local clock does not change the server-derived date.
await page.evaluate(()=>{Date.now=()=>4102444800000;LanguageMinerDailyGolem.practice({id:'last'});});assert.equal(await page.evaluate(()=>state.dailyGolem.day),'2026-09-24');assert.equal(await page.evaluate(()=>state.dailyGolem.questions),5);
// A second browser tab/device has the same cloud revision, then races the claim.
await page.evaluate(()=>languageMinerPushCloudSave());const second=await ctx.newPage();await second.goto('http://127.0.0.1:8765/index.html');await second.waitForFunction(()=>state.dailyGolem?.questions===5);const results=await Promise.all([page.evaluate(()=>languageMinerCommitDailyGolem('2026-09-24').then(()=>true,()=>false)),second.evaluate(()=>languageMinerCommitDailyGolem('2026-09-24').then(()=>true,()=>false))]);assert.equal(commits,1);assert.equal(row.game_state.dailyGolem.claims,1);assert.equal(results.filter(Boolean).length,1);console.log('concurrent devices: exactly one grant',results);
assert.equal(row.game_state.dailyGolem.streak,1,'Racing claims advance the daily reward streak only once');assert.equal(errors.length,0);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});

