const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});const ctx=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});let serverDay='2026-09-24',row=null,commits=0;const errors=[];
await ctx.route('**/*.supabase.co/**',async route=>{const url=route.request().url();let value=[];if(url.includes('/rpc/save_player_state')){const p=route.request().postDataJSON();if(row&&row.revision!==p.p_base_revision)value=[{...row,accepted:false}];else{if(p.p_game_state.dailyGolem?.claims>(row?.game_state?.dailyGolem?.claims||0))commits++;row={user_id:'golem-qa',game_state:p.p_game_state,course_settings:p.p_course_settings,revision:(row?.revision||0)+1,updated_at:serverDay+'T12:00:00.000Z'};value=[{...row,accepted:true}];}}else if(url.includes('/rpc/load_player_save'))value=row?[row]:[];else if(url.includes('/auth/v1/user'))value={id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});});
await ctx.addInitScript(()=>{if(!localStorage.getItem('jm_profiles')){localStorage.setItem('jm_profiles',JSON.stringify([{id:'cloud-golem-qa',name:'Golem QA',cloudUserId:'golem-qa'}]));localStorage.setItem('jm_active_profile','cloud-golem-qa');localStorage.setItem('lm_multilingual_functional_preview_v1:cloud:golem-qa',JSON.stringify({known:'en',learning:'ja',placements:{ja:{status:'tested'}}}));localStorage.setItem('jm_profile_cloud-golem-qa',JSON.stringify({onboardingComplete:true,placementTestCompleted:true,voiceEnabled:false,autoSpeak:false,hearts:14,maxHearts:14}));}localStorage.setItem('lm_cloud_session_v2',JSON.stringify({accessToken:'qa-test',refreshToken:'qa-refresh',expiresAt:9999999999,user:{id:'golem-qa',email:'qa@example.invalid',user_metadata:{display_name:'Golem QA',account_role:'adult_guardian',terms_version:'2026-08-15-v1',privacy_version:'2026-08-15-v1'}}}));});
const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.PRACTICE_TEST_URL||'http://127.0.0.1:8765/')+'index.html');await page.waitForFunction(()=>window.LanguageMinerDailyGolem&&typeof state!=='undefined'&&state.dailyGolem?.day);if(await page.locator('#lmMultilingualOverlay.open').count())await page.locator('#lmFlowClose').click();await page.screenshot({path:'work/golem-initial.png',fullPage:true});console.log('loaded',await page.locator('#dailyGolem').innerText());

assert(!await page.locator('#patreonHeartRewardLauncher').isVisible());
await page.evaluate(()=>{state.practiceMode='reading';state.shieldArmed=false;state.developerInfiniteHearts=false;state.active={...questions.find(q=>q.stage===0)};state.answered=false;showQuestion(state.active);});
const before=await page.evaluate(()=>state.hearts);const wrong=await page.evaluate(()=>[...document.querySelectorAll('#answers button')].find(b=>b.textContent!==state.active.a).textContent);await page.locator('#answers').getByRole('button',{name:wrong,exact:true}).click();
assert.equal(await page.evaluate(()=>state.hearts),before-1);const launcher=page.locator('#patreonHeartRewardLauncher');assert(await launcher.isVisible());assert(await launcher.isEnabled());assert.match(await launcher.innerText(),/Restore your heart/);
await page.setViewportSize({width:390,height:844});const box=await launcher.boundingBox();assert(box.x>=0&&box.x+box.width<=390&&box.y+box.height<=844);await launcher.click();await page.locator('[data-patreon-video-tier="1"]').click();await page.getByText('+1 heart earned!',{exact:true}).waitFor({timeout:45000});assert.equal(await page.evaluate(()=>state.hearts),before);await page.locator('#patreonVideoResultClose').click();assert(!await launcher.isVisible());
await page.evaluate(()=>{state.hearts--;save();});assert(await launcher.isVisible());assert(await launcher.isDisabled());assert.match(await launcher.innerText(),/Available in/);await page.evaluate(()=>{state.patreonHeartVideoReward.lastClaimedAt=0;save();});assert(await launcher.isEnabled());assert.equal(errors.length,0,errors.join(';'));console.log('PASS immediate loss, mobile button, complete video +1 heart, full hearts, cooldown and expiry');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
