"""Build 17 recorded-language variants from current game art. Resumable TTS cache.

Requires Pillow, PyAV, edge-tts and imageio-ffmpeg. Run from the repository root.
Captions are rendered by the player, so the shared artwork has no English copy.
"""
from pathlib import Path
import asyncio, hashlib, json, os, subprocess, sys
from concurrent.futures import ThreadPoolExecutor

for directory in os.environ.get('REEL_PYTHON_DEPS', '').split(os.pathsep):
    if directory: sys.path.insert(0, directory)
import edge_tts
import av
import imageio_ffmpeg
from PIL import Image, ImageDraw, ImageFilter, ImageOps

ROOT = Path(__file__).resolve().parents[2]
WORK = ROOT / 'work/reward-reels-v285'
OUT = ROOT / 'patreon-reels/v285'
WORK.mkdir(parents=True, exist_ok=True)
OUT.mkdir(parents=True, exist_ok=True)
FF = imageio_ffmpeg.get_ffmpeg_exe()
VOICES = dict(en='en-US-JennyNeural', ja='ja-JP-NanamiNeural', ko='ko-KR-SunHiNeural',
    zh='zh-CN-XiaoxiaoNeural', es='es-ES-ElviraNeural', fr='fr-FR-DeniseNeural',
    de='de-DE-KatjaNeural', it='it-IT-ElsaNeural', pt='pt-BR-FranciscaNeural',
    ru='ru-RU-SvetlanaNeural', uk='uk-UA-PolinaNeural', pl='pl-PL-ZofiaNeural',
    el='el-GR-AthinaNeural', tr='tr-TR-EmelNeural', id='id-ID-GadisNeural',
    vi='vi-VN-HoaiMyNeural', th='th-TH-PremwadeeNeural')
DATA = json.loads((ROOT/'tools/reward-reels/scripts.json').read_text(encoding='utf-8'))
UI = json.loads((ROOT/'tools/reward-reels/ui.json').read_text(encoding='utf-8'))
for language, copy in DATA['languages'].items():
    assert len(UI[language]) == len(UI['keys'])
    copy['ui'] = dict(zip(UI['keys'], UI[language]))
(ROOT/'patreon-reel-locales.js').write_text('// Generated by tools/reward-reels/build.py\nwindow.LanguageMinerPatreonReelLocales='+json.dumps(DATA,ensure_ascii=False)+';\n',encoding='utf-8')

def run(args):
    result = subprocess.run([FF, '-hide_banner', '-loglevel', 'error', '-y', *map(str,args)], capture_output=True)
    if result.returncode: raise RuntimeError(result.stderr.decode('utf-8', errors='replace'))

async def narration():
    limit = asyncio.Semaphore(6)
    async def clip(lang, index, text):
        key = hashlib.sha256((VOICES[lang] + text).encode()).hexdigest()[:16]
        target = WORK/f'{lang}-{index}-{key}.mp3'
        if target.exists() and target.stat().st_size > 500: return
        async with limit:
            for attempt in range(4):
                try:
                    temp = target.with_suffix('.tmp.mp3')
                    await edge_tts.Communicate(text, VOICES[lang]).save(str(temp))
                    if temp.stat().st_size < 500: raise ValueError('Empty narration')
                    temp.replace(target)
                    print(f'Voice {lang} {index+1}/12', flush=True)
                    return
                except Exception:
                    if attempt == 3: raise
                    await asyncio.sleep(2 ** attempt)
    await asyncio.gather(*(clip(lang, i, text) for lang, copy in DATA['languages'].items() for i,text in enumerate(copy['lines'])))

def frame(tier, index, asset):
    accent = ['#70f2c8','#8bb8ff','#d89cff'][tier-1]
    bg = ImageOps.fit(Image.open(ROOT/'adventure-world.png').convert('RGB'), (960,540)).filter(ImageFilter.GaussianBlur(7)).convert('RGBA')
    bg = Image.alpha_composite(bg,Image.new('RGBA',bg.size,(4,12,27,200)))
    draw=ImageDraw.Draw(bg)
    draw.rounded_rectangle((30,22,930,496),radius=28,fill='#14243a',outline=accent,width=3)
    art=Image.open(ROOT/asset).convert('RGBA')
    if tier==3 and index==1:
        width,height=art.size
        art=art.crop((int(width*.22),int(height*.28),int(width*.78),int(height*.76)))
    # The character screenshot is a portrait of the current rendered avatar.
    art=ImageOps.contain(art,(850,440))
    bg.alpha_composite(art,((960-art.width)//2,259-art.height//2))
    draw=ImageDraw.Draw(bg)
    for k in range(4):draw.rounded_rectangle((392+k*46,514,422+k*46,519),radius=2,fill=accent if index==k else '#40536b')
    target=WORK/f'tier{tier}-scene{index}.png';bg.convert('RGB').save(target)
    return target

def visuals():
    assets=[
        ['tools/reward-reels/scenes/character.png','tools/reward-reels/scenes/mine-cosmetics.png',
         'menu-wallpapers/art-azure-passage-v2.webp','menu-wallpapers/art-amethyst-dream-v2.webp'],
        ['companion-3d-kitsune.png','companion-3d-cat.png','avatar-holiday-summer-matsuri-v1.png','companion-3d-dragon.png'],
        ['settlement-village-map-v1.png','settlement-village-map-v1.png',
         'tools/reward-reels/scenes/arcade.png','adventure-world.png']]
    for tier,scenes in enumerate(assets,1):
        parts=[]
        for index,asset in enumerate(scenes):
            png=frame(tier,index,asset)
            if index==0:Image.open(png).save(OUT/f'tier-{tier}.jpg',quality=88)
            part=WORK/f'visual-{tier}-{index}.mp4';parts.append(part)
            # Slow camera movement and fades use the same four six-second scenes.
            run(['-loop','1','-i',png,'-vf',"zoompan=z='min(zoom+0.0002,1.025)':x='iw/2-iw/zoom/2':y='ih/2-ih/zoom/2':d=144:s=960x540:fps=24,fade=t=in:d=0.25,fade=t=out:st=5.75:d=0.25,format=yuv420p",'-t','6','-an','-c:v','libx264','-preset','fast','-crf','23',part])
        listing=WORK/f'visual-{tier}.txt'
        listing.write_text(''.join(f"file '{p.as_posix()}'\n" for p in parts))
        run(['-f','concat','-safe','0','-i',listing,'-c','copy',WORK/f'visual-{tier}.mp4'])
        print(f'Visual tier {tier}',flush=True)

def encode_language(lang):
    for tier in range(1,4):
        inputs=[];filters=[]
        for index in range((tier-1)*4,tier*4):
            text=DATA['languages'][lang]['lines'][index]
            key=hashlib.sha256((VOICES[lang]+text).encode()).hexdigest()[:16]
            source=WORK/f'{lang}-{index}-{key}.mp3'
            with av.open(str(source)) as audio:
                stream=audio.streams.audio[0]
                seconds=float(stream.duration*stream.time_base)
            tempo=max(1,seconds/5.65)
            part=index%4
            inputs.extend(['-i',source])
            filters.append(f'[{part+1}:a]atempo={tempo},apad,atrim=duration=6,asetpts=PTS-STARTPTS[a{part}]')
        filters.append('[a0][a1][a2][a3]concat=n=4:v=0:a=1[a]')
        folder=OUT/lang;folder.mkdir(exist_ok=True)
        # Recorded native-language narration is embedded in each MP4: one clock,
        # native pause/mute support, and no dependency on installed device voices.
        run(['-i',WORK/f'visual-{tier}.mp4',*inputs,'-filter_complex',';'.join(filters),
             '-map','0:v','-map','[a]','-c:v','copy','-c:a','aac','-b:a','64k',
             '-metadata:s:a:0',f'language={lang}','-t','24','-movflags','+faststart',folder/f'tier-{tier}.mp4'])
        print(f'Video {lang} tier {tier}',flush=True)

if __name__=='__main__':
    asyncio.run(narration())
    if '--voices-only' not in sys.argv:
        if '--encode-only' not in sys.argv: visuals()
        with ThreadPoolExecutor(max_workers=3) as pool:list(pool.map(encode_language,DATA['languages']))
        manifest={'version':DATA['version'],'durationSeconds':24,'languages':list(DATA['languages']),
                  'voices':VOICES,'files':{str(p.relative_to(OUT)).replace('\\','/'):{'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in OUT.rglob('*.mp4')}}
        (OUT/'manifest.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
